---@diagnostic disable: undefined-global

-- autogenerated lush spec on di 25 jan 17:34:43 2022
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function()
  return {
    SpecialKey                             { fg="#e1e4e8", }, -- SpecialKey     xxx ctermfg=81 guifg=#e1e4e8
    EndOfBuffer                            { fg="#24292e", }, -- EndOfBuffer    xxx guifg=#24292e
    DiffviewEndOfBuffer                    { EndOfBuffer }, -- DiffviewEndOfBuffer xxx links to EndOfBuffer
    TermCursor                             { gui="reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    NonText                                { fg="#24292e", }, -- NonText        xxx ctermfg=12 guifg=#24292e
    DiffviewNonText                        { NonText }, -- DiffviewNonText xxx links to NonText
    TelescopePromptCounter                 { NonText }, -- TelescopePromptCounter xxx links to NonText
    TelescopePreviewHyphen                 { NonText }, -- TelescopePreviewHyphen xxx links to NonText
    TelescopeResultsDiffUntracked          { NonText }, -- TelescopeResultsDiffUntracked xxx links to NonText
    Directory                              { fg="#2188ff", }, -- Directory      xxx ctermfg=159 guifg=#2188ff
    TroubleFile                            { Directory }, -- TroubleFile    xxx links to Directory
    DiffviewFolderName                     { Directory }, -- DiffviewFolderName xxx links to Directory
    NvimTreeEmptyFolderName                { Directory }, -- NvimTreeEmptyFolderName xxx links to Directory
    TelescopePreviewDirectory              { Directory }, -- TelescopePreviewDirectory xxx links to Directory
    TelescopePreviewDate                   { Directory }, -- TelescopePreviewDate xxx links to Directory
    ErrorMsg                               { fg="#f97583", }, -- ErrorMsg       xxx ctermfg=15 ctermbg=1 guifg=#f97583
    NvimInvalidSpacing                     { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    CocErrorSign                           { ErrorMsg }, -- CocErrorSign   xxx links to ErrorMsg
    CocErrorFloat                          { ErrorMsg }, -- CocErrorFloat  xxx links to ErrorMsg
    CocDiagnosticsError                    { ErrorMsg }, -- CocDiagnosticsError xxx links to ErrorMsg
    IncSearch                              { gui="reverse", }, -- IncSearch      xxx cterm=reverse gui=reverse
    Search                                 { bg="#404030", }, -- Search         xxx ctermfg=0 ctermbg=11 guibg=#404030
    TroublePreview                         { Search }, -- TroublePreview xxx links to Search
    TelescopePreviewMatch                  { Search }, -- TelescopePreviewMatch xxx links to Search
    MoreMsg                                { fg="#2188ff", }, -- MoreMsg        xxx ctermfg=121 guifg=#2188ff
    ModeMsg                                { gui="bold", fg="#c9d1d9", }, -- ModeMsg        xxx cterm=bold gui=bold guifg=#c9d1d9
    LineNr                                 { fg="#444d56", }, -- LineNr         xxx ctermfg=11 guifg=#444d56
    LineNrAbove                            { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                            { LineNr }, -- LineNrBelow    xxx links to LineNr
    TroubleIndent                          { LineNr }, -- TroubleIndent  xxx links to LineNr
    TroubleLocation                        { LineNr }, -- TroubleLocation xxx links to LineNr
    TelescopeResultsLineNr                 { LineNr }, -- TelescopeResultsLineNr xxx links to LineNr
    CursorLineNr                           { fg="#e1e4e8", }, -- CursorLineNr   xxx cterm=underline ctermfg=11 guifg=#e1e4e8
    TroubleFoldIcon                        { CursorLineNr }, -- TroubleFoldIcon xxx links to CursorLineNr
    Question                               { fg="#2188ff", }, -- Question       xxx ctermfg=121 guifg=#2188ff
    StatusLine                             { gui="underline", sp="#444c56", fg="#24292e", bg="#24292e", }, -- StatusLine     xxx cterm=bold,reverse gui=underline guifg=#24292e guibg=#24292e guisp=#444c56
    MsgSeparator                           { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    DiffviewStatusLine                     { StatusLine }, -- DiffviewStatusLine xxx links to StatusLine
    NvimTreeStatusLine                     { StatusLine }, -- NvimTreeStatusLine xxx links to StatusLine
    StatusLineNC                           { gui="underline", sp="#444c56", fg="#24292e", bg="#24292e", }, -- StatusLineNC   xxx cterm=reverse gui=underline guifg=#24292e guibg=#24292e guisp=#444c56
    DiffviewStatusLineNC                   { StatusLineNC }, -- DiffviewStatusLineNC xxx links to StatusLineNC
    NvimTreeStatusLineNC                   { StatusLineNC }, -- NvimTreeStatusLineNC xxx links to StatusLineNC
    VertSplit                              { fg="#444c56", bg="#24292e", }, -- VertSplit      xxx cterm=reverse guifg=#444c56 guibg=#24292e
    DiffviewVertSplit                      { VertSplit }, -- DiffviewVertSplit xxx links to VertSplit
    NvimTreeVertSplit                      { VertSplit }, -- NvimTreeVertSplit xxx links to VertSplit
    Title                                  { gui="bold", fg="#79b8ff", }, -- Title          xxx ctermfg=225 gui=bold guifg=#79b8ff
    TSTitle                                { Title }, -- TSTitle        xxx links to Title
    Visual                                 { bg="#284566", }, -- Visual         xxx ctermbg=242 guibg=#284566
    VisualNOS                              { Visual }, -- VisualNOS      xxx links to Visual
    CocHighlightText                       { Visual }, -- CocHighlightText xxx links to Visual
    TSPlaygroundFocus                      { Visual }, -- TSPlaygroundFocus xxx links to Visual
    TelescopeSelection                     { Visual }, -- TelescopeSelection xxx links to Visual
    TelescopePreviewLine                   { Visual }, -- TelescopePreviewLine xxx links to Visual
    WarningMsg                             { fg="#cca700", }, -- WarningMsg     xxx ctermfg=224 guifg=#cca700
    CocWarningSign                         { WarningMsg }, -- CocWarningSign xxx links to WarningMsg
    CocWarningFloat                        { WarningMsg }, -- CocWarningFloat xxx links to WarningMsg
    CocDiagnosticsWarning                  { WarningMsg }, -- CocDiagnosticsWarning xxx links to WarningMsg
    WildMenu                               { bg="#444c56", }, -- WildMenu       xxx ctermfg=0 ctermbg=11 guibg=#444c56
    Folded                                 { fg="#c9d1d9", bg="#284566", }, -- Folded         xxx ctermfg=14 ctermbg=242 guifg=#c9d1d9 guibg=#284566
    FoldColumn                             { fg="cyan", bg="grey", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
    DiffAdd                                { fg="#56d364", bg="#244032", }, -- DiffAdd        xxx ctermbg=4 guifg=#56d364 guibg=#244032
    NeogitDiffAddHighlight                 { DiffAdd }, -- NeogitDiffAddHighlight xxx links to DiffAdd
    diffAdded                              { DiffAdd }, -- diffAdded      xxx links to DiffAdd
    TelescopeResultsDiffAdd                { DiffAdd }, -- TelescopeResultsDiffAdd xxx links to DiffAdd
    DiffChange                             { fg="#e3b341", bg="#341a00", }, -- DiffChange     xxx ctermbg=5 guifg=#e3b341 guibg=#341a00
    diffChanged                            { DiffChange }, -- diffChanged    xxx links to DiffChange
    TelescopeResultsDiffChange             { DiffChange }, -- TelescopeResultsDiffChange xxx links to DiffChange
    DiffDelete                             { fg="#f85149", bg="#462c32", }, -- DiffDelete     xxx ctermfg=12 ctermbg=6 guifg=#f85149 guibg=#462c32
    NeogitDiffDeleteHighlight              { DiffDelete }, -- NeogitDiffDeleteHighlight xxx links to DiffDelete
    diffRemoved                            { DiffDelete }, -- diffRemoved    xxx links to DiffDelete
    TelescopeResultsDiffDelete             { DiffDelete }, -- TelescopeResultsDiffDelete xxx links to DiffDelete
    DiffText                               { fg="#e1e4e8", }, -- DiffText       xxx cterm=bold ctermbg=9 guifg=#e1e4e8
    SignColumn                             { fg="#e1e4e8", bg="#24292e", }, -- SignColumn     xxx ctermfg=14 ctermbg=242 guifg=#e1e4e8 guibg=#24292e
    Conceal                                { fg="#e1e4e8", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=#e1e4e8
    SpellBad                               { gui="undercurl", sp="#f97583", }, -- SpellBad       xxx ctermbg=9 gui=undercurl guisp=#f97583
    SpellCap                               { gui="undercurl", sp="#cca700", }, -- SpellCap       xxx ctermbg=12 gui=undercurl guisp=#cca700
    SpellRare                              { gui="undercurl", sp="#eeeeb3", }, -- SpellRare      xxx ctermbg=13 gui=undercurl guisp=#eeeeb3
    SpellLocal                             { gui="undercurl", sp="#75beff", }, -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=#75beff
    Pmenu                                  { fg="#c9d1d9", bg="#1f2428", }, -- Pmenu          xxx ctermfg=0 ctermbg=13 guifg=#c9d1d9 guibg=#1f2428
    PmenuSel                               { fg="#1f2428", bg="#6494cb", }, -- PmenuSel       xxx ctermfg=242 ctermbg=0 guifg=#1f2428 guibg=#6494CB
    PmenuSbar                              { bg="#1f2428", }, -- PmenuSbar      xxx ctermbg=248 guibg=#1f2428
    PmenuThumb                             { bg="#32383e", }, -- PmenuThumb     xxx ctermbg=15 guibg=#32383e
    TabLine                                { fg="#c9d1d9", bg="#24292e", }, -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 guifg=#c9d1d9 guibg=#24292e
    TabLineSel                             { gui="bold", }, -- TabLineSel     xxx cterm=bold gui=bold
    TroubleCount                           { TabLineSel }, -- TroubleCount   xxx links to TabLineSel
    TabLineFill                            { bg="#1f2428", }, -- TabLineFill    xxx cterm=reverse guibg=#1f2428
    CursorColumn                           { bg="#2c313a", }, -- CursorColumn   xxx ctermbg=242 guibg=#2c313a
    NvimTreeCursorColumn                   { CursorColumn }, -- NvimTreeCursorColumn xxx links to CursorColumn
    CursorLine                             { bg="grey40", }, -- CursorLine     xxx cterm=underline guibg=Grey40
    DiffviewCursorLine                     { CursorLine }, -- DiffviewCursorLine xxx links to CursorLine
    NvimTreeCursorLine                     { CursorLine }, -- NvimTreeCursorLine xxx links to CursorLine
    ColorColumn                            { bg="#444c56", }, -- ColorColumn    xxx ctermbg=1 guibg=#444c56
    QuickFixLine                           { gui="bold", bg="#233c58", }, -- QuickFixLine   xxx gui=bold guibg=#233C58
    Whitespace                             { fg="#40474e", }, -- Whitespace     xxx guifg=#40474E
    NormalNC                               { fg="#c9d1d9", bg="#24292e", }, -- NormalNC       xxx guifg=#c9d1d9 guibg=#24292e
    NormalFloat                            { fg="#c9d1d9", bg="#24292e", }, -- NormalFloat    xxx guifg=#c9d1d9 guibg=#24292e
    MsgArea                                { fg="#c9d1d9", }, -- MsgArea        xxx guifg=#c9d1d9
    FloatBorder                            { fg="#c9d1d9", }, -- FloatBorder    xxx guifg=#c9d1d9
    RedrawDebugNormal                      { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                       { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                    { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                   { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Cursor                                 { fg="#24292e", bg="#c9d1d9", }, -- Cursor         xxx guifg=#24292e guibg=#c9d1d9
    CursorIM                               { Cursor }, -- CursorIM       xxx links to Cursor
    lCursor                                { fg="bg", bg="fg", }, -- lCursor        xxx guifg=bg guibg=fg
    Normal                                 { fg="#c9d1d9", bg="#24292e", }, -- Normal         xxx guifg=#c9d1d9 guibg=#24292e
    NvimSpacing                            { Normal }, -- NvimSpacing    xxx links to Normal
    TroubleText                            { Normal }, -- TroubleText    xxx links to Normal
    TroubleNormal                          { Normal }, -- TroubleNormal  xxx links to Normal
    DiffviewNormal                         { Normal }, -- DiffviewNormal xxx links to Normal
    DiffviewSignColumn                     { Normal }, -- DiffviewSignColumn xxx links to Normal
    NvimTreePopup                          { Normal }, -- NvimTreePopup  xxx links to Normal
    RenamerNormal                          { Normal }, -- RenamerNormal  xxx links to Normal
    TelescopeNormal                        { Normal }, -- TelescopeNormal xxx links to Normal
    Substitute                             { fg="#586069", bg="#ea4a5a", }, -- Substitute     xxx guifg=#586069 guibg=#ea4a5a
    FloatShadow                            { blend="80", bg="black", }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                     { blend="100", bg="black", }, -- FloatShadowThrough xxx guibg=Black blend=100
    Error                                  { fg="#f97583", }, -- Error          xxx ctermfg=15 ctermbg=9 guifg=#f97583
    NvimInvalid                            { Error }, -- NvimInvalid    xxx links to Error
    TSQueryLinterError                     { Error }, -- TSQueryLinterError xxx links to Error
    luaParenError                          { Error }, -- luaParenError  xxx links to Error
    luaBraceError                          { Error }, -- luaBraceError  xxx links to Error
    luaError                               { Error }, -- luaError       xxx links to Error
    Todo                                   { fg="#24292e", bg="#ffea7f", }, -- Todo           xxx ctermfg=0 ctermbg=11 guifg=#24292e guibg=#ffea7f
    luaTodo                                { Todo }, -- luaTodo        xxx links to Todo
    String                                 { fg="#9ecbff", }, -- String         xxx guifg=#9ecbff
    NvimString                             { String }, -- NvimString     xxx links to String
    TSString                               { String }, -- TSString       xxx links to String
    TSLiteral                              { String }, -- TSLiteral      xxx links to String
    TSPlaygroundLang                       { String }, -- TSPlaygroundLang xxx links to String
    TelescopePreviewExecute                { String }, -- TelescopePreviewExecute xxx links to String
    TelescopePreviewSize                   { String }, -- TelescopePreviewSize xxx links to String
    luaString2                             { String }, -- luaString2     xxx links to String
    luaString                              { String }, -- luaString      xxx links to String
    Constant                               { fg="#79b8ff", }, -- Constant       xxx ctermfg=13 guifg=#79b8ff
    Number                                 { Constant }, -- Number         xxx links to Constant
    Boolean                                { Constant }, -- Boolean        xxx links to Constant
    TelescopePreviewPipe                   { Constant }, -- TelescopePreviewPipe xxx links to Constant
    TelescopePreviewCharDev                { Constant }, -- TelescopePreviewCharDev xxx links to Constant
    TelescopePreviewBlock                  { Constant }, -- TelescopePreviewBlock xxx links to Constant
    TelescopePreviewRead                   { Constant }, -- TelescopePreviewRead xxx links to Constant
    TelescopePreviewUser                   { Constant }, -- TelescopePreviewUser xxx links to Constant
    TelescopePreviewGroup                  { Constant }, -- TelescopePreviewGroup xxx links to Constant
    TelescopeResultsConstant               { Constant }, -- TelescopeResultsConstant xxx links to Constant
    luaConstant                            { Constant }, -- luaConstant    xxx links to Constant
    Character                              { fg="#79b8ff", }, -- Character      xxx guifg=#79b8ff
    TSCharacter                            { Character }, -- TSCharacter    xxx links to Character
    lualine_17_no_mode                     { Character }, -- lualine_17_no_mode xxx links to Character
    Function                               { gui="italic", fg="#b392f0", }, -- Function       xxx gui=italic guifg=#b392f0
    TSFunction                             { Function }, -- TSFunction     xxx links to Function
    TSMethod                               { Function }, -- TSMethod       xxx links to Function
    TelescopeResultsClass                  { Function }, -- TelescopeResultsClass xxx links to Function
    TelescopeResultsField                  { Function }, -- TelescopeResultsField xxx links to Function
    TelescopeResultsFunction               { Function }, -- TelescopeResultsFunction xxx links to Function
    luaFunction                            { Function }, -- luaFunction    xxx links to Function
    Identifier                             { fg="#79b8ff", }, -- Identifier     xxx cterm=bold ctermfg=14 guifg=#79b8ff
    NvimIdentifier                         { Identifier }, -- NvimIdentifier xxx links to Identifier
    TSSymbol                               { Identifier }, -- TSSymbol       xxx links to Identifier
    RenamerTitle                           { Identifier }, -- RenamerTitle   xxx links to Identifier
    TelescopeMultiIcon                     { Identifier }, -- TelescopeMultiIcon xxx links to Identifier
    TelescopeResultsIdentifier             { Identifier }, -- TelescopeResultsIdentifier xxx links to Identifier
    luaFunc                                { Identifier }, -- luaFunc        xxx links to Identifier
    Statement                              { fg="#f97583", }, -- Statement      xxx ctermfg=11 guifg=#f97583
    Conditional                            { Statement }, -- Conditional    xxx links to Statement
    Repeat                                 { Statement }, -- Repeat         xxx links to Statement
    Label                                  { Statement }, -- Label          xxx links to Statement
    Exception                              { Statement }, -- Exception      xxx links to Statement
    TelescopePreviewSocket                 { Statement }, -- TelescopePreviewSocket xxx links to Statement
    TelescopePreviewWrite                  { Statement }, -- TelescopePreviewWrite xxx links to Statement
    luaStatement                           { Statement }, -- luaStatement   xxx links to Statement
    Operator                               { fg="#f97583", }, -- Operator       xxx guifg=#f97583
    NvimAssignment                         { Operator }, -- NvimAssignment xxx links to Operator
    NvimOperator                           { Operator }, -- NvimOperator   xxx links to Operator
    CmpItemKindOperatorDefault             { Operator }, -- CmpItemKindOperatorDefault xxx links to Operator
    TelescopeResultsOperator               { Operator }, -- TelescopeResultsOperator xxx links to Operator
    luaIn                                  { Operator }, -- luaIn          xxx links to Operator
    luaOperator                            { Operator }, -- luaOperator    xxx links to Operator
    Keyword                                { gui="italic", fg="#f97583", }, -- Keyword        xxx gui=italic guifg=#f97583
    TelescopePreviewSticky                 { Keyword }, -- TelescopePreviewSticky xxx links to Keyword
    PreProc                                { fg="#f97583", }, -- PreProc        xxx ctermfg=81 guifg=#f97583
    Include                                { PreProc }, -- Include        xxx links to PreProc
    Define                                 { PreProc }, -- Define         xxx links to PreProc
    Macro                                  { PreProc }, -- Macro          xxx links to PreProc
    PreCondit                              { PreProc }, -- PreCondit      xxx links to PreProc
    DiffviewFolderSign                     { PreProc }, -- DiffviewFolderSign xxx links to PreProc
    TSAnnotation                           { PreProc }, -- TSAnnotation   xxx links to PreProc
    TSAttribute                            { PreProc }, -- TSAttribute    xxx links to PreProc
    Type                                   { fg="#f97583", }, -- Type           xxx ctermfg=121 guifg=#f97583
    StorageClass                           { Type }, -- StorageClass   xxx links to Type
    Structure                              { Type }, -- Structure      xxx links to Type
    Typedef                                { Type }, -- Typedef        xxx links to Type
    NvimNumberPrefix                       { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                        { Type }, -- NvimOptionSigil xxx links to Type
    TSTypeBuiltin                          { Type }, -- TSTypeBuiltin  xxx links to Type
    TSEnvironmentName                      { Type }, -- TSEnvironmentName xxx links to Type
    Special                                { fg="#79b8ff", }, -- Special        xxx ctermfg=224 guifg=#79b8ff
    Tag                                    { Special }, -- Tag            xxx links to Special
    SpecialChar                            { Special }, -- SpecialChar    xxx links to Special
    Delimiter                              { Special }, -- Delimiter      xxx links to Special
    SpecialComment                         { Special }, -- SpecialComment xxx links to Special
    Debug                                  { Special }, -- Debug          xxx links to Special
    NotifyLogTitle                         { Special }, -- NotifyLogTitle xxx links to Special
    TSConstBuiltin                         { Special }, -- TSConstBuiltin xxx links to Special
    TSFuncBuiltin                          { Special }, -- TSFuncBuiltin  xxx links to Special
    TSMath                                 { Special }, -- TSMath         xxx links to Special
    TelescopePreviewLink                   { Special }, -- TelescopePreviewLink xxx links to Special
    DiagnosticError                        { fg="#f97583", }, -- DiagnosticError xxx ctermfg=1 guifg=#f97583
    DiagnosticVirtualTextError             { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticFloatingError                { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticSignError                    { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    TroubleError                           { DiagnosticError }, -- TroubleError   xxx links to DiagnosticError
    NvimTreeLspDiagnosticsError            { DiagnosticError }, -- NvimTreeLspDiagnosticsError xxx links to DiagnosticError
    DiagnosticWarn                         { fg="orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticVirtualTextWarn              { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticFloatingWarn                 { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticSignWarn                     { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    TroubleWarning                         { DiagnosticWarn }, -- TroubleWarning xxx links to DiagnosticWarn
    NvimTreeLspDiagnosticsWarning          { DiagnosticWarn }, -- NvimTreeLspDiagnosticsWarning xxx links to DiagnosticWarn
    DiagnosticInfo                         { fg="lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticVirtualTextInfo              { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticFloatingInfo                 { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticSignInfo                     { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    TroubleInformation                     { DiagnosticInfo }, -- TroubleInformation xxx links to DiagnosticInfo
    CocInfoSign                            { DiagnosticInfo }, -- CocInfoSign    xxx links to DiagnosticInfo
    CocInfoFloat                           { DiagnosticInfo }, -- CocInfoFloat   xxx links to DiagnosticInfo
    CocDiagnosticsInfo                     { DiagnosticInfo }, -- CocDiagnosticsInfo xxx links to DiagnosticInfo
    NvimTreeLspDiagnosticsInformation      { DiagnosticInfo }, -- NvimTreeLspDiagnosticsInformation xxx links to DiagnosticInfo
    DiagnosticHint                         { fg="#eeeeb3", }, -- DiagnosticHint xxx ctermfg=7 guifg=#eeeeb3
    DiagnosticVirtualTextHint              { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticFloatingHint                 { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticSignHint                     { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    TroubleHint                            { DiagnosticHint }, -- TroubleHint    xxx links to DiagnosticHint
    CocHintSign                            { DiagnosticHint }, -- CocHintSign    xxx links to DiagnosticHint
    CocHintFloat                           { DiagnosticHint }, -- CocHintFloat   xxx links to DiagnosticHint
    CocDiagnosticsHint                     { DiagnosticHint }, -- CocDiagnosticsHint xxx links to DiagnosticHint
    NvimTreeLspDiagnosticsHint             { DiagnosticHint }, -- NvimTreeLspDiagnosticsHint xxx links to DiagnosticHint
    DiagnosticUnderlineError               { gui="underline", sp="red", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineWarn                { gui="underline", sp="orange", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticUnderlineInfo                { gui="underline", sp="lightblue", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineHint                { gui="underline", sp="lightgrey", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    MatchParen                             { fg="#c9d1d9", bg="#25686c", }, -- MatchParen     xxx ctermbg=6 guifg=#c9d1d9 guibg=#25686c
    Comment                                { gui="italic", fg="#6a737d", }, -- Comment        xxx ctermfg=14 gui=italic guifg=#6a737d
    NotifyLogTime                          { Comment }, -- NotifyLogTime  xxx links to Comment
    TroubleSource                          { Comment }, -- TroubleSource  xxx links to Comment
    TroubleCode                            { Comment }, -- TroubleCode    xxx links to Comment
    DiffviewDiffDelete                     { Comment }, -- DiffviewDiffDelete xxx links to Comment
    DiffviewFilePanelPath                  { Comment }, -- DiffviewFilePanelPath xxx links to Comment
    DiffviewStatusIgnored                  { Comment }, -- DiffviewStatusIgnored xxx links to Comment
    TSComment                              { Comment }, -- TSComment      xxx links to Comment
    TelescopeResultsComment                { Comment }, -- TelescopeResultsComment xxx links to Comment
    luaComment                             { Comment }, -- luaComment     xxx links to Comment
    Underlined                             { gui="underline", }, -- Underlined     xxx cterm=underline ctermfg=81 gui=underline
    TSURI                                  { Underlined }, -- TSURI          xxx links to Underlined
    Ignore                                 { fg="bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                      { fg="red", bg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                        { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape          { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape   { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    NotifyERRORTitle                       { fg="#e46d7b", }, -- NotifyERRORTitle xxx guifg=#E46D7B
    NotifyERRORBorder                      { NotifyERRORTitle }, -- NotifyERRORBorder xxx links to NotifyERRORTitle
    NotifyERRORIcon                        { NotifyERRORTitle }, -- NotifyERRORIcon xxx links to NotifyERRORTitle
    NotifyWARNTitle                        { fg="#bb9a05", }, -- NotifyWARNTitle xxx guifg=#BB9A05
    NotifyWARNBorder                       { NotifyWARNTitle }, -- NotifyWARNBorder xxx links to NotifyWARNTitle
    NotifyWARNIcon                         { NotifyWARNTitle }, -- NotifyWARNIcon xxx links to NotifyWARNTitle
    NotifyINFOTitle                        { fg="#32bf54", }, -- NotifyINFOTitle xxx guifg=#32BF54
    NotifyINFOBorder                       { NotifyINFOTitle }, -- NotifyINFOBorder xxx links to NotifyINFOTitle
    NotifyINFOIcon                         { NotifyINFOTitle }, -- NotifyINFOIcon xxx links to NotifyINFOTitle
    NotifyDEBUGTitle                       { fg="#989fa6", }, -- NotifyDEBUGTitle xxx guifg=#989FA6
    NotifyDEBUGBorder                      { NotifyDEBUGTitle }, -- NotifyDEBUGBorder xxx links to NotifyDEBUGTitle
    NotifyDEBUGIcon                        { NotifyDEBUGTitle }, -- NotifyDEBUGIcon xxx links to NotifyDEBUGTitle
    NotifyDEBUGBody                        { NotifyDEBUGTitle }, -- NotifyDEBUGBody xxx links to NotifyDEBUGTitle
    NotifyTRACETitle                       { fg="#a588dd", }, -- NotifyTRACETitle xxx guifg=#A588DD
    NotifyTRACEBorder                      { NotifyTRACETitle }, -- NotifyTRACEBorder xxx links to NotifyTRACETitle
    NotifyTRACEIcon                        { NotifyTRACETitle }, -- NotifyTRACEIcon xxx links to NotifyTRACETitle
    NotifyERRORBody                        { fg="#cec8d0", }, -- NotifyERRORBody xxx guifg=#CEC8D0
    NotifyWARNBody                         { fg="#c9cdc3", }, -- NotifyWARNBody xxx guifg=#C9CDC3
    NotifyINFOBody                         { fg="#bad1cc", }, -- NotifyINFOBody xxx guifg=#BAD1CC
    NotifyTRACEBody                        { fg="#c7cbdb", }, -- NotifyTRACEBody xxx guifg=#C7CBDB
    NeogitHunkHeader                       { fg="#c9d1d9", bg="#2c313a", }, -- NeogitHunkHeader xxx guifg=#c9d1d9 guibg=#2c313a
    NeogitHunkHeaderHighlight              { gui="italic", fg="#2188ff", bg="#2c313a", }, -- NeogitHunkHeaderHighlight xxx gui=italic guifg=#2188ff guibg=#2c313a
    NeogitDiffContextHighlight             { fg="#c9d1d9", bg="#24292e", }, -- NeogitDiffContextHighlight xxx guifg=#c9d1d9 guibg=#24292e
    LspDiagnosticsVirtualTextHint          { fg="#eeeeb3", bg="#383d3b", }, -- LspDiagnosticsVirtualTextHint xxx guifg=#eeeeb3 guibg=#383D3B
    LspDiagnosticsUnderlineInformation     { gui="undercurl", sp="#75beff", }, -- LspDiagnosticsUnderlineInformation xxx gui=undercurl guisp=#75beff
    CocInfoHighlight                       { LspDiagnosticsUnderlineInformation }, -- CocInfoHighlight xxx links to LspDiagnosticsUnderlineInformation
    LspDiagnosticsUnderlineWarning         { gui="undercurl", sp="#cca700", }, -- LspDiagnosticsUnderlineWarning xxx gui=undercurl guisp=#cca700
    CocWarningHighlight                    { LspDiagnosticsUnderlineWarning }, -- CocWarningHighlight xxx links to LspDiagnosticsUnderlineWarning
    LspDiagnosticsUnderlineError           { gui="undercurl", sp="#f97583", }, -- LspDiagnosticsUnderlineError xxx gui=undercurl guisp=#f97583
    CocErrorHighlight                      { LspDiagnosticsUnderlineError }, -- CocErrorHighlight xxx links to LspDiagnosticsUnderlineError
    SignColumnSB                           { fg="#e1e4e8", bg="#24292e", }, -- SignColumnSB   xxx guifg=#e1e4e8 guibg=#24292e
    Bold                                   { gui="bold", }, -- Bold           xxx gui=bold
    LspDiagnosticsDefaultInformation       { fg="#75beff", }, -- LspDiagnosticsDefaultInformation xxx guifg=#75beff
    LspDiagnosticsDefaultWarning           { fg="#cca700", }, -- LspDiagnosticsDefaultWarning xxx guifg=#cca700
    LspDiagnosticsDefaultError             { fg="#f97583", }, -- LspDiagnosticsDefaultError xxx guifg=#f97583
    LspDiagnosticsWarning                  { fg="#cca700", }, -- LspDiagnosticsWarning xxx guifg=#cca700
    LspDiagnosticsHint                     { fg="#eeeeb3", }, -- LspDiagnosticsHint xxx guifg=#eeeeb3
    LspDiagnosticsInformation              { fg="#75beff", }, -- LspDiagnosticsInformation xxx guifg=#75beff
    LspDiagnosticsError                    { fg="#f97583", }, -- LspDiagnosticsError xxx guifg=#f97583
    LspReferenceText                       { bg="#265459", }, -- LspReferenceText xxx guibg=#265459
    LspReferenceWrite                      { LspReferenceText }, -- LspReferenceWrite xxx links to LspReferenceText
    LspReferenceRead                       { LspReferenceText }, -- LspReferenceRead xxx links to LspReferenceText
    qfLineNr                               { fg="#f97583", }, -- qfLineNr       xxx guifg=#f97583
    qfFileName                             { fg="#2188ff", }, -- qfFileName     xxx guifg=#2188ff
    mkdCodeDelimiter                       { fg="#c9d1d9", }, -- mkdCodeDelimiter xxx guifg=#c9d1d9
    mkdCodeStart                           { gui="bold", fg="#79b8ff", }, -- mkdCodeStart   xxx gui=bold guifg=#79b8ff
    mkdCodeEnd                             { gui="bold", fg="#79b8ff", }, -- mkdCodeEnd     xxx gui=bold guifg=#79b8ff
    markdownHeadingDelimiter               { gui="bold", fg="#79b8ff", }, -- markdownHeadingDelimiter xxx gui=bold guifg=#79b8ff
    markdownH1                             { gui="bold", fg="#79b8ff", }, -- markdownH1     xxx gui=bold guifg=#79b8ff
    markdownH2                             { gui="bold", fg="#79b8ff", }, -- markdownH2     xxx gui=bold guifg=#79b8ff
    markdownH3                             { gui="bold", fg="#79b8ff", }, -- markdownH3     xxx gui=bold guifg=#79b8ff
    markdownLinkText                       { gui="underline", fg="#c9d1d9", }, -- markdownLinkText xxx gui=underline guifg=#c9d1d9
    markdownUrl                            { gui="underline", fg="#c9d1d9", }, -- markdownUrl    xxx gui=underline guifg=#c9d1d9
    debugPC                                { bg="#24292e", }, -- debugPC        xxx guibg=#24292e
    debugBreakpoint                        { fg="#75beff", bg="#2c3843", }, -- debugBreakpoint xxx guifg=#75beff guibg=#2C3843
    LspDiagnosticsVirtualTextWarning       { fg="#cca700", bg="#353629", }, -- LspDiagnosticsVirtualTextWarning xxx guifg=#cca700 guibg=#353629
    Italic                                 { gui="italic", }, -- Italic         xxx gui=italic
    LspDiagnosticsDefaultHint              { fg="#eeeeb3", }, -- LspDiagnosticsDefaultHint xxx guifg=#eeeeb3
    LspDiagnosticsVirtualTextError         { fg="#f97583", bg="#393137", }, -- LspDiagnosticsVirtualTextError xxx guifg=#f97583 guibg=#393137
    LspDiagnosticsVirtualTextInformation   { fg="#75beff", bg="#2c3843", }, -- LspDiagnosticsVirtualTextInformation xxx guifg=#75beff guibg=#2C3843
    LspDiagnosticsUnderlineHint            { gui="undercurl", sp="#eeeeb3", }, -- LspDiagnosticsUnderlineHint xxx gui=undercurl guisp=#eeeeb3
    CocHintHighlight                       { LspDiagnosticsUnderlineHint }, -- CocHintHighlight xxx links to LspDiagnosticsUnderlineHint
    NormalSB                               { fg="#c9d1d9", bg="#24292e", }, -- NormalSB       xxx guifg=#c9d1d9 guibg=#24292e
    typescriptTSType                       { fg="#b392f0", }, -- typescriptTSType xxx guifg=#b392f0
    typescriptTSConstructor                { fg="#b392f0", }, -- typescriptTSConstructor xxx guifg=#b392f0
    typescriptTSTypeBuiltin                { fg="#79b8ff", }, -- typescriptTSTypeBuiltin xxx guifg=#79b8ff
    xmlProcessing                          { fg="#85e89d", }, -- xmlProcessing  xxx guifg=#85e89d
    xmlTagName                             { fg="#85e89d", }, -- xmlTagName     xxx guifg=#85e89d
    xmlTag                                 { fg="#c9d1d9", }, -- xmlTag         xxx guifg=#c9d1d9
    xmlAttrib                              { fg="#85e89d", }, -- xmlAttrib      xxx guifg=#85e89d
    yamlTSField                            { fg="#85e89d", }, -- yamlTSField    xxx guifg=#85e89d
    javaTSVariable                         { fg="#c9d1d9", }, -- javaTSVariable xxx guifg=#c9d1d9
    javaTSType                             { fg="#b392f0", }, -- javaTSType     xxx guifg=#b392f0
    javaTSParameter                        { fg="#ffab70", }, -- javaTSParameter xxx guifg=#ffab70
    markdownHeadingRule                    { fg="#79b8ff", }, -- markdownHeadingRule xxx guifg=#79b8ff
    markdownListMarker                     { fg="#ffab70", }, -- markdownListMarker xxx guifg=#ffab70
    markdownRule                           { fg="#79b8ff", }, -- markdownRule   xxx guifg=#79b8ff
    markdownBold                           { gui="bold", fg="#c9d1d9", }, -- markdownBold   xxx gui=bold guifg=#c9d1d9
    markdownItalic                         { gui="italic", fg="#c9d1d9", }, -- markdownItalic xxx gui=italic guifg=#c9d1d9
    markdownCode                           { fg="#c9d1d9", }, -- markdownCode   xxx guifg=#c9d1d9
    markdownCodeBlock                      { fg="#c9d1d9", }, -- markdownCodeBlock xxx guifg=#c9d1d9
    markdownBlockquote                     { fg="#85e89d", }, -- markdownBlockquote xxx guifg=#85e89d
    markdownCodeDelimiter                  { fg="#b392f0", }, -- markdownCodeDelimiter xxx guifg=#b392f0
    markdownUrlTitle                       { gui="underline", fg="#9ecbff", }, -- markdownUrlTitle xxx gui=underline guifg=#9ecbff
    goTSVariable                           { fg="#c9d1d9", }, -- goTSVariable   xxx guifg=#c9d1d9
    LspTroubleText                         { fg="#c9d1d9", }, -- LspTroubleText xxx guifg=#c9d1d9
    LspTroubleCount                        { fg="#b392f0", bg="#e1e4e8", }, -- LspTroubleCount xxx guifg=#b392f0 guibg=#e1e4e8
    LspTroubleNormal                       { fg="#ffea7f", bg="#24292e", }, -- LspTroubleNormal xxx guifg=#ffea7f guibg=#24292e
    illuminatedWord                        { bg="#265459", }, -- illuminatedWord xxx guibg=#265459
    illuminatedCurWord                     { bg="#265459", }, -- illuminatedCurWord xxx guibg=#265459
    diffOldFile                            { fg="#ffea7f", }, -- diffOldFile    xxx guifg=#ffea7f
    diffNewFile                            { fg="#d18616", }, -- diffNewFile    xxx guifg=#d18616
    diffFile                               { fg="#2188ff", }, -- diffFile       xxx guifg=#2188ff
    diffLine                               { fg="#e1e4e8", }, -- diffLine       xxx guifg=#e1e4e8
    diffIndexLine                          { fg="#b392f0", }, -- diffIndexLine  xxx guifg=#b392f0
    NeogitBranch                           { fg="#f97583", }, -- NeogitBranch   xxx guifg=#f97583
    NeogitRemote                           { fg="#f97583", }, -- NeogitRemote   xxx guifg=#f97583
    GitGutterAdd                           { fg="#28a745", }, -- GitGutterAdd   xxx guifg=#28a745
    GitGutterChange                        { fg="#2188ff", }, -- GitGutterChange xxx guifg=#2188ff
    GitGutterDelete                        { fg="#ea4a5a", }, -- GitGutterDelete xxx guifg=#ea4a5a
    GitSignsAdd                            { fg="#28a745", }, -- GitSignsAdd    xxx guifg=#28a745
    GitSignsChange                         { fg="#2188ff", }, -- GitSignsChange xxx guifg=#2188ff
    GitSignsDelete                         { fg="#ea4a5a", }, -- GitSignsDelete xxx guifg=#ea4a5a
    GitSignsCurrentLineBlame               { fg="#4e555d", }, -- GitSignsCurrentLineBlame xxx guifg=#4E555D
    NvimTreeNormal                         { fg="#d1d5da", bg="#24292e", }, -- NvimTreeNormal xxx guifg=#d1d5da guibg=#24292e
    NvimTreeSignColumn                     { NvimTreeNormal }, -- NvimTreeSignColumn xxx links to NvimTreeNormal
    NvimTreeNormalNC                       { NvimTreeNormal }, -- NvimTreeNormalNC xxx links to NvimTreeNormal
    NvimTreeEndOfBuffer                    { fg="#24292e", }, -- NvimTreeEndOfBuffer xxx guifg=#24292e
    NvimTreeRootFolder                     { gui="bold", fg="#d1d5da", }, -- NvimTreeRootFolder xxx gui=bold guifg=#d1d5da
    NvimTreeGitDirty                       { fg="#e2c08d", }, -- NvimTreeGitDirty xxx guifg=#e2c08d
    NvimTreeFileDirty                      { NvimTreeGitDirty }, -- NvimTreeFileDirty xxx links to NvimTreeGitDirty
    NvimTreeGitNew                         { fg="#34d058", }, -- NvimTreeGitNew xxx guifg=#34d058
    NvimTreeFileNew                        { NvimTreeGitNew }, -- NvimTreeFileNew xxx links to NvimTreeGitNew
    NvimTreeGitRenamed                     { fg="#73c991", }, -- NvimTreeGitRenamed xxx guifg=#73c991
    NvimTreeFileRenamed                    { NvimTreeGitRenamed }, -- NvimTreeFileRenamed xxx links to NvimTreeGitRenamed
    NvimTreeGitDeleted                     { fg="#ea4a5a", }, -- NvimTreeGitDeleted xxx guifg=#ea4a5a
    NvimTreeFileDeleted                    { NvimTreeGitDeleted }, -- NvimTreeFileDeleted xxx links to NvimTreeGitDeleted
    NvimTreeGitIgnored                     { fg="#6a737d", }, -- NvimTreeGitIgnored xxx guifg=#6a737d
    NvimTreeSpecialFile                    { gui="underline", fg="#ffea7f", }, -- NvimTreeSpecialFile xxx gui=underline guifg=#ffea7f
    NvimTreeIndentMarker                   { fg="#6a737d", }, -- NvimTreeIndentMarker xxx guifg=#6a737d
    NvimTreeImageFile                      { fg="#ffea7f", }, -- NvimTreeImageFile xxx guifg=#ffea7f
    NvimTreeSymlink                        { fg="#b392f0", }, -- NvimTreeSymlink xxx guifg=#b392f0
    NvimTreeFolderName                     { fg="#d1d5da", }, -- NvimTreeFolderName xxx guifg=#d1d5da
    NvimTreeOpenedFolderName               { gui="bold", fg="#d1d5da", }, -- NvimTreeOpenedFolderName xxx gui=bold guifg=#d1d5da
    gitcommitSummary                       { fg="#85e89d", }, -- gitcommitSummary xxx guifg=#85e89d
    TelescopeMultiSelection                { fg="#6a737d", }, -- TelescopeMultiSelection xxx guifg=#6a737d
    DashboardCenter                        { gui="bold", fg="#34d058", }, -- DashboardCenter xxx gui=bold guifg=#34d058
    TSParameter                            { fg="#e1e4e8", }, -- TSParameter    xxx guifg=#e1e4e8
    TSParameterReference                   { TSParameter }, -- TSParameterReference xxx links to TSParameter
    DashboardFooter                        { gui="italic", fg="#fafbfc", }, -- DashboardFooter xxx gui=italic guifg=#fafbfc
    TSProperty                             { fg="#b392f0", }, -- TSProperty     xxx guifg=#b392f0
    TSTagAttribute                         { TSProperty }, -- TSTagAttribute xxx links to TSProperty
    TSVariableBuiltin                      { fg="#79b8ff", }, -- TSVariableBuiltin xxx guifg=#79b8ff
    WhichKeyGroup                          { fg="#f97583", }, -- WhichKeyGroup  xxx guifg=#f97583
    WhichKeySeperator                      { fg="#6a737d", }, -- WhichKeySeperator xxx guifg=#6a737d
    WhichKeySeparator                      { WhichKeySeperator }, -- WhichKeySeparator xxx links to WhichKeySeperator
    WhichKeyDesc                           { fg="#c9d1d9", }, -- WhichKeyDesc   xxx guifg=#c9d1d9
    WhichKeyFloat                          { bg="#1f2428", }, -- WhichKeyFloat  xxx guibg=#1f2428
    WhichKeyValue                          { fg="#6a737d", }, -- WhichKeyValue  xxx guifg=#6a737d
    DiagnosticWarning                      { fg="#cca700", }, -- DiagnosticWarning xxx guifg=#cca700
    DiagnosticInformation                  { fg="#75beff", }, -- DiagnosticInformation xxx guifg=#75beff
    healthError                            { fg="#f97583", }, -- healthError    xxx guifg=#f97583
    TelescopePromptPrefix                  { fg="#c9d1d9", }, -- TelescopePromptPrefix xxx guifg=#c9d1d9
    healthWarning                          { fg="#cca700", }, -- healthWarning  xxx guifg=#cca700
    BufferLineIndicatorSelected            { fg="#2188ff", }, -- BufferLineIndicatorSelected xxx guifg=#2188ff
    BufferLineFill                         { bg="#1f2428", }, -- BufferLineFill xxx guibg=#1f2428
    HopNextKey                             { gui="bold", fg="#b392f0", }, -- HopNextKey     xxx gui=bold guifg=#b392f0
    HopNextKey1                            { gui="bold", fg="#2188ff", }, -- HopNextKey1    xxx gui=bold guifg=#2188ff
    HopNextKey2                            { fg="#689bd5", }, -- HopNextKey2    xxx guifg=#689BD5
    HopUnmatched                           { fg="#666666", }, -- HopUnmatched   xxx guifg=#666666
    ALEErrorSign                           { fg="#f97583", }, -- ALEErrorSign   xxx guifg=#f97583
    CmpItemKindColorDefault                { fg="#f97583", }, -- CmpItemKindColorDefault xxx guifg=#f97583
    CmpItemKindColor                       { CmpItemKindColorDefault }, -- CmpItemKindColor xxx links to CmpItemKindColorDefault
    CmpItemKindPropertyDefault             { fg="#b392f0", }, -- CmpItemKindPropertyDefault xxx guifg=#b392f0
    CmpItemKindProperty                    { CmpItemKindPropertyDefault }, -- CmpItemKindProperty xxx links to CmpItemKindPropertyDefault
    CmpItemKindSnippetDefault              { fg="#ffea7f", }, -- CmpItemKindSnippetDefault xxx guifg=#ffea7f
    CmpItemKindSnippet                     { CmpItemKindSnippetDefault }, -- CmpItemKindSnippet xxx links to CmpItemKindSnippetDefault
    CmpItemKindVariableDefault             { fg="#79b8ff", }, -- CmpItemKindVariableDefault xxx guifg=#79b8ff
    CmpItemKindClassDefault                { CmpItemKindVariableDefault }, -- CmpItemKindClassDefault xxx links to CmpItemKindVariableDefault
    CmpItemKindEnumDefault                 { CmpItemKindVariableDefault }, -- CmpItemKindEnumDefault xxx links to CmpItemKindVariableDefault
    CmpItemKindInterfaceDefault            { CmpItemKindVariableDefault }, -- CmpItemKindInterfaceDefault xxx links to CmpItemKindVariableDefault
    CmpItemKindTextDefault                 { CmpItemKindVariableDefault }, -- CmpItemKindTextDefault xxx links to CmpItemKindVariableDefault
    CmpItemKindVariable                    { CmpItemKindVariableDefault }, -- CmpItemKindVariable xxx links to CmpItemKindVariableDefault
    CmpItemKindKeywordDefault              { fg="#f97583", }, -- CmpItemKindKeywordDefault xxx guifg=#f97583
    CmpItemKindFieldDefault                { CmpItemKindKeywordDefault }, -- CmpItemKindFieldDefault xxx links to CmpItemKindKeywordDefault
    CmpItemKindUnitDefault                 { CmpItemKindKeywordDefault }, -- CmpItemKindUnitDefault xxx links to CmpItemKindKeywordDefault
    CmpItemKindValueDefault                { CmpItemKindKeywordDefault }, -- CmpItemKindValueDefault xxx links to CmpItemKindKeywordDefault
    CmpItemKindKeyword                     { CmpItemKindKeywordDefault }, -- CmpItemKindKeyword xxx links to CmpItemKindKeywordDefault
    CmpItemKindFileDefault                 { fg="#d18616", }, -- CmpItemKindFileDefault xxx guifg=#d18616
    CmpItemKindFolderDefault               { CmpItemKindFileDefault }, -- CmpItemKindFolderDefault xxx links to CmpItemKindFileDefault
    CmpItemKindFile                        { CmpItemKindFileDefault }, -- CmpItemKindFile xxx links to CmpItemKindFileDefault
    CmpItemKindFunctionDefault             { fg="#b392f0", }, -- CmpItemKindFunctionDefault xxx guifg=#b392f0
    CmpItemKindConstructorDefault          { CmpItemKindFunctionDefault }, -- CmpItemKindConstructorDefault xxx links to CmpItemKindFunctionDefault
    CmpItemKindEventDefault                { CmpItemKindFunctionDefault }, -- CmpItemKindEventDefault xxx links to CmpItemKindFunctionDefault
    CmpItemKindMethodDefault               { CmpItemKindFunctionDefault }, -- CmpItemKindMethodDefault xxx links to CmpItemKindFunctionDefault
    CmpItemKindFunction                    { CmpItemKindFunctionDefault }, -- CmpItemKindFunction xxx links to CmpItemKindFunctionDefault
    CmpItemKindConstantDefault             { fg="#79b8ff", }, -- CmpItemKindConstantDefault xxx guifg=#79b8ff
    CmpItemKindModuleDefault               { CmpItemKindConstantDefault }, -- CmpItemKindModuleDefault xxx links to CmpItemKindConstantDefault
    CmpItemKindStructDefault               { CmpItemKindConstantDefault }, -- CmpItemKindStructDefault xxx links to CmpItemKindConstantDefault
    CmpItemKindTypeParameterDefault        { CmpItemKindConstantDefault }, -- CmpItemKindTypeParameterDefault xxx links to CmpItemKindConstantDefault
    CmpItemKindConstant                    { CmpItemKindConstantDefault }, -- CmpItemKindConstant xxx links to CmpItemKindConstantDefault
    TelescopeBorder                        { fg="#c9d1d9", }, -- TelescopeBorder xxx guifg=#c9d1d9
    TelescopePromptBorder                  { TelescopeBorder }, -- TelescopePromptBorder xxx links to TelescopeBorder
    TelescopeResultsBorder                 { TelescopeBorder }, -- TelescopeResultsBorder xxx links to TelescopeBorder
    TelescopePreviewBorder                 { TelescopeBorder }, -- TelescopePreviewBorder xxx links to TelescopeBorder
    TelescopeTitle                         { TelescopeBorder }, -- TelescopeTitle xxx links to TelescopeBorder
    CocUnderline                           { gui="undercurl", }, -- CocUnderline   xxx gui=undercurl
    TSNote                                 { fg="#24292e", bg="#75beff", }, -- TSNote         xxx guifg=#24292e guibg=#75beff
    TSWarning                              { fg="#24292e", bg="#cca700", }, -- TSWarning      xxx guifg=#24292e guibg=#cca700
    TSDanger                               { fg="#24292e", bg="#f97583", }, -- TSDanger       xxx guifg=#24292e guibg=#f97583
    TSConstructor                          { fg="#79b8ff", }, -- TSConstructor  xxx guifg=#79b8ff
    commentTSConstant                      { fg="#f97583", }, -- commentTSConstant xxx guifg=#f97583
    TSInclude                              { fg="#f97583", }, -- TSInclude      xxx guifg=#f97583
    TSKeyword                              { gui="italic", fg="#f97583", }, -- TSKeyword      xxx gui=italic guifg=#f97583
    TSKeywordReturn                        { TSKeyword }, -- TSKeywordReturn xxx links to TSKeyword
    luaTSKeyword                           { TSKeyword }, -- luaTSKeyword   xxx links to TSKeyword
    TSKeywordFunction                      { gui="italic", fg="#f97583", }, -- TSKeywordFunction xxx gui=italic guifg=#f97583
    luaTSKeywordFunction                   { TSKeywordFunction }, -- luaTSKeywordFunction xxx links to TSKeywordFunction
    TSLabel                                { fg="#2188ff", }, -- TSLabel        xxx guifg=#2188ff
    TSNamespace                            { fg="#c9d1d9", }, -- TSNamespace    xxx guifg=#c9d1d9
    TSOperator                             { fg="#f97583", }, -- TSOperator     xxx guifg=#f97583
    TSKeywordOperator                      { TSOperator }, -- TSKeywordOperator xxx links to TSOperator
    luaTSOperator                          { TSOperator }, -- luaTSOperator  xxx links to TSOperator
    TSPunctDelimiter                       { fg="#c9d1d9", }, -- TSPunctDelimiter xxx guifg=#c9d1d9
    luaTSPunctDelimiter                    { TSPunctDelimiter }, -- luaTSPunctDelimiter xxx links to TSPunctDelimiter
    TSPunctBracket                         { fg="#c9d1d9", }, -- TSPunctBracket xxx guifg=#c9d1d9
    luaTSPunctBracket                      { TSPunctBracket }, -- luaTSPunctBracket xxx links to TSPunctBracket
    TSPunctSpecial                         { fg="#c9d1d9", }, -- TSPunctSpecial xxx guifg=#c9d1d9
    TSStringRegex                          { fg="#79b8ff", }, -- TSStringRegex  xxx guifg=#79b8ff
    TSStringEscape                         { fg="#ea4a5a", }, -- TSStringEscape xxx guifg=#ea4a5a
    TSType                                 { fg="#f97583", }, -- TSType         xxx guifg=#f97583
    TSVariable                             { fg="#79b8ff", }, -- TSVariable     xxx guifg=#79b8ff
    luaTSVariable                          { TSVariable }, -- luaTSVariable  xxx links to TSVariable
    TSTag                                  { fg="#85e89d", }, -- TSTag          xxx guifg=#85e89d
    TSTagDelimiter                         { fg="#c9d1d9", }, -- TSTagDelimiter xxx guifg=#c9d1d9
    TSTextReference                        { fg="#ea4a5a", }, -- TSTextReference xxx guifg=#ea4a5a
    luaTSConstructor                       { fg="#c9d1d9", }, -- luaTSConstructor xxx guifg=#c9d1d9
    cTSLabel                               { fg="#c9d1d9", }, -- cTSLabel       xxx guifg=#c9d1d9
    cssTSProperty                          { fg="#b392f0", }, -- cssTSProperty  xxx guifg=#b392f0
    cssTSType                              { fg="#85e89d", }, -- cssTSType      xxx guifg=#85e89d
    htmlTSConstant                         { fg="#85e89d", }, -- htmlTSConstant xxx guifg=#85e89d
    htmlTag                                { fg="#c9d1d9", }, -- htmlTag        xxx guifg=#c9d1d9
    htmlEndTag                             { fg="#c9d1d9", }, -- htmlEndTag     xxx guifg=#c9d1d9
    htmlTagName                            { fg="#85e89d", }, -- htmlTagName    xxx guifg=#85e89d
    htmlArg                                { fg="#fdaeb7", }, -- htmlArg        xxx guifg=#fdaeb7
    javascriptTSType                       { fg="#c9d1d9", }, -- javascriptTSType xxx guifg=#c9d1d9
    javascriptTSParameter                  { fg="#ffab70", }, -- javascriptTSParameter xxx guifg=#ffab70
    CocCodeLens                            { fg="#666666", }, -- CocCodeLens    xxx guifg=#666666
    javascriptTSVariable                   { fg="#79b8ff", }, -- javascriptTSVariable xxx guifg=#79b8ff
    javascriptTSPunctDelimiter             { fg="#c9d1d9", }, -- javascriptTSPunctDelimiter xxx guifg=#c9d1d9
    javascriptTSStringRegex                { fg="#9ecbff", }, -- javascriptTSStringRegex xxx guifg=#9ecbff
    TelescopeMatching                      { gui="bold", fg="#79b8ff", }, -- TelescopeMatching xxx gui=bold guifg=#79b8ff
    javascriptTSProperty                   { fg="#b392f0", }, -- javascriptTSProperty xxx guifg=#b392f0
    regexTSStringEscape                    { fg="#f97583", }, -- regexTSStringEscape xxx guifg=#f97583
    jsonTSLabel                            { fg="#79b8ff", }, -- jsonTSLabel    xxx guifg=#79b8ff
    CocSelectedText                        { fg="#ea4a5a", }, -- CocSelectedText xxx guifg=#ea4a5a
    lessVariable                           { fg="#c9d1d9", }, -- lessVariable   xxx guifg=#c9d1d9
    lessProperty                           { fg="#79b8ff", }, -- lessProperty   xxx guifg=#79b8ff
    cssTagName                             { fg="#85e89d", }, -- cssTagName     xxx guifg=#85e89d
    cssPseudoClassId                       { fg="#b392f0", }, -- cssPseudoClassId xxx guifg=#b392f0
    lessClassCall                          { fg="#b392f0", }, -- lessClassCall  xxx guifg=#b392f0
    lessClass                              { fg="#b392f0", }, -- lessClass      xxx guifg=#b392f0
    makeSpecial                            { fg="#f97583", }, -- makeSpecial    xxx guifg=#f97583
    cBlock                                 { fg="#b392f0", }, -- cBlock         xxx guifg=#b392f0
    pythonTSType                           { fg="#b392f0", }, -- pythonTSType   xxx guifg=#b392f0
    pythonTSParameter                      { fg="#ffab70", }, -- pythonTSParameter xxx guifg=#ffab70
    rubyTSType                             { fg="#b392f0", }, -- rubyTSType     xxx guifg=#b392f0
    scssTSVariable                         { fg="#ffab70", }, -- scssTSVariable xxx guifg=#ffab70
    scssTSType                             { fg="#85e89d", }, -- scssTSType     xxx guifg=#85e89d
    scssTSProperty                         { fg="#b392f0", }, -- scssTSProperty xxx guifg=#b392f0
    scssTSParameter                        { fg="#ffab70", }, -- scssTSParameter xxx guifg=#ffab70
    sqlFold                                { fg="#79b8ff", }, -- sqlFold        xxx guifg=#79b8ff
    sqlKeyword                             { fg="#f97583", }, -- sqlKeyword     xxx guifg=#f97583
    CmpItemAbbrMatch                       { fg="#2188ff", }, -- CmpItemAbbrMatch xxx guifg=#2188ff
    CmpItemAbbrMatchFuzzy                  { CmpItemAbbrMatch }, -- CmpItemAbbrMatchFuzzy xxx links to CmpItemAbbrMatch
    CmpItemAbbrDeprecated                  { gui="strikethrough", fg="#6a737d", }, -- CmpItemAbbrDeprecated xxx gui=strikethrough guifg=#6a737d
    ALEWarningSign                         { fg="#cca700", }, -- ALEWarningSign xxx guifg=#cca700
    healthSuccess                          { fg="#34d058", }, -- healthSuccess  xxx guifg=#34d058
    WhichKey                               { fg="#2188ff", }, -- WhichKey       xxx guifg=#2188ff
    DashboardShortCut                      { fg="#ffea7f", }, -- DashboardShortCut xxx guifg=#ffea7f
    DashboardHeader                        { fg="#2188ff", }, -- DashboardHeader xxx guifg=#2188ff
    javascriptTSConstructor                { fg="#b392f0", }, -- javascriptTSConstructor xxx guifg=#b392f0
    TSField                                { fg="#c9d1d9", }, -- TSField        xxx guifg=#c9d1d9
    luaTSField                             { TSField }, -- luaTSField     xxx links to TSField
    TSConstant                             { fg="#79b8ff", }, -- TSConstant     xxx guifg=#79b8ff
    DiffviewDiffAddAsDelete                { fg="#f85149", bg="#462c32", }, -- DiffviewDiffAddAsDelete xxx guifg=#f85149 guibg=#462c32
    DiffviewFilePanelTitle                 { gui="bold", fg="#2188ff", }, -- DiffviewFilePanelTitle xxx gui=bold guifg=#2188ff
    DiffviewFilePanelRootPath              { DiffviewFilePanelTitle }, -- DiffviewFilePanelRootPath xxx links to DiffviewFilePanelTitle
    DiffviewFilePanelCounter               { gui="bold", fg="#79b8ff", }, -- DiffviewFilePanelCounter xxx gui=bold guifg=#79b8ff
    DiffviewFilePanelFileName              { fg="#c9d1d9", }, -- DiffviewFilePanelFileName xxx guifg=#c9d1d9
    DiffviewDim1                           { fg="#6a737d", }, -- DiffviewDim1   xxx guifg=#6a737d
    DiffviewPrimary                        { fg="#79b8ff", }, -- DiffviewPrimary xxx guifg=#79b8ff
    DiffviewSecondary                      { fg="#79b8ff", }, -- DiffviewSecondary xxx guifg=#79b8ff
    DevIconSql                             { fg="#dad8d8", }, -- DevIconSql     xxx ctermfg=188 guifg=#dad8d8
    DevIconDoc                             { fg="#185abd", }, -- DevIconDoc     xxx ctermfg=25 guifg=#185abd
    DevIconD                               { fg="#427819", }, -- DevIconD       xxx ctermfg=64 guifg=#427819
    DevIconZshrc                           { fg="#89e051", }, -- DevIconZshrc   xxx ctermfg=113 guifg=#89e051
    DevIconRmd                             { fg="#519aba", }, -- DevIconRmd     xxx ctermfg=67 guifg=#519aba
    DevIconSlim                            { fg="#e34c26", }, -- DevIconSlim    xxx ctermfg=166 guifg=#e34c26
    DevIconImportConfiguration             { fg="#ececec", }, -- DevIconImportConfiguration xxx ctermfg=231 guifg=#ECECEC
    DevIconTwig                            { fg="#8dc149", }, -- DevIconTwig    xxx ctermfg=107 guifg=#8dc149
    DevIconGitModules                      { fg="#41535b", }, -- DevIconGitModules xxx ctermfg=59 guifg=#41535b
    DevIconMaterial                        { fg="#b83998", }, -- DevIconMaterial xxx ctermfg=132 guifg=#B83998
    DevIconLhs                             { fg="#a074c4", }, -- DevIconLhs     xxx ctermfg=140 guifg=#a074c4
    DevIconMjs                             { fg="#f1e05a", }, -- DevIconMjs     xxx ctermfg=221 guifg=#f1e05a
    DevIconOpenTypeFont                    { fg="#ececec", }, -- DevIconOpenTypeFont xxx ctermfg=231 guifg=#ECECEC
    DevIconZshenv                          { fg="#89e051", }, -- DevIconZshenv  xxx ctermfg=113 guifg=#89e051
    DevIconTex                             { fg="#3d6117", }, -- DevIconTex     xxx ctermfg=58 guifg=#3D6117
    DevIconCsh                             { fg="#4d5a5e", }, -- DevIconCsh     xxx ctermfg=59 guifg=#4d5a5e
    DevIconVimrc                           { fg="#019833", }, -- DevIconVimrc   xxx ctermfg=29 guifg=#019833
    DevIconOPUS                            { fg="#f88a02", }, -- DevIconOPUS    xxx ctermfg=208 guifg=#F88A02
    DevIconKsh                             { fg="#4d5a5e", }, -- DevIconKsh     xxx ctermfg=59 guifg=#4d5a5e
    DevIconGitLogo                         { fg="#f14c28", }, -- DevIconGitLogo xxx ctermfg=202 guifg=#F14C28
    DevIconCMake                           { fg="#6d8086", }, -- DevIconCMake   xxx ctermfg=66 guifg=#6d8086
    DevIconCPlusPlus                       { fg="#f34b7d", }, -- DevIconCPlusPlus xxx ctermfg=204 guifg=#f34b7d
    DevIconMint                            { fg="#87c095", }, -- DevIconMint    xxx ctermfg=108 guifg=#87c095
    DevIconJpg                             { fg="#a074c4", }, -- DevIconJpg     xxx ctermfg=140 guifg=#a074c4
    DevIconJpeg                            { fg="#a074c4", }, -- DevIconJpeg    xxx ctermfg=140 guifg=#a074c4
    DevIconBash                            { fg="#89e051", }, -- DevIconBash    xxx ctermfg=113 guifg=#89e051
    DevIconGif                             { fg="#a074c4", }, -- DevIconGif     xxx ctermfg=140 guifg=#a074c4
    DevIconIco                             { fg="#cbcb41", }, -- DevIconIco     xxx ctermfg=185 guifg=#cbcb41
    DevIconCp                              { fg="#519aba", }, -- DevIconCp      xxx ctermfg=67 guifg=#519aba
    DevIconRakefile                        { fg="#701516", }, -- DevIconRakefile xxx ctermfg=52 guifg=#701516
    DevIconPhp                             { fg="#a074c4", }, -- DevIconPhp     xxx ctermfg=140 guifg=#a074c4
    DevIconPpt                             { fg="#cb4a32", }, -- DevIconPpt     xxx ctermfg=167 guifg=#cb4a32
    DevIconMl                              { fg="#e37933", }, -- DevIconMl      xxx ctermfg=173 guifg=#e37933
    DevIconHrl                             { fg="#b83998", }, -- DevIconHrl     xxx ctermfg=132 guifg=#B83998
    DevIconRb                              { fg="#701516", }, -- DevIconRb      xxx ctermfg=52 guifg=#701516
    DevIconJava                            { fg="#cc3e44", }, -- DevIconJava    xxx ctermfg=167 guifg=#cc3e44
    DevIconClojureC                        { fg="#8dc149", }, -- DevIconClojureC xxx ctermfg=107 guifg=#8dc149
    DevIconLua                             { fg="#51a0cf", }, -- DevIconLua     xxx ctermfg=74 guifg=#51a0cf
    DevIconLeex                            { fg="#a074c4", }, -- DevIconLeex    xxx ctermfg=140 guifg=#a074c4
    DevIconHaml                            { fg="#eaeae1", }, -- DevIconHaml    xxx ctermfg=188 guifg=#eaeae1
    DevIconCss                             { fg="#563d7c", }, -- DevIconCss     xxx ctermfg=60 guifg=#563d7c
    DevIconProcfile                        { fg="#a074c4", }, -- DevIconProcfile xxx ctermfg=140 guifg=#a074c4
    DevIconErl                             { fg="#b83998", }, -- DevIconErl     xxx ctermfg=132 guifg=#B83998
    DevIconLicense                         { fg="#cbcb41", }, -- DevIconLicense xxx ctermfg=185 guifg=#cbcb41
    DevIconMixLock                         { fg="#a074c4", }, -- DevIconMixLock xxx ctermfg=140 guifg=#a074c4
    DevIconSuo                             { fg="#e37933", }, -- DevIconSuo     xxx ctermfg=98 guifg=#e37933
    DevIconZsh                             { fg="#89e051", }, -- DevIconZsh     xxx ctermfg=113 guifg=#89e051
    DevIconIni                             { fg="#6d8086", }, -- DevIconIni     xxx ctermfg=66 guifg=#6d8086
    DevIconCobol                           { fg="#005ca5", }, -- DevIconCobol   xxx ctermfg=25 guifg=#005ca5
    DevIconHeex                            { fg="#a074c4", }, -- DevIconHeex    xxx ctermfg=140 guifg=#a074c4
    DevIconPp                              { fg="#ffa61a", }, -- DevIconPp      xxx guifg=#FFA61A
    DevIconDsStore                         { fg="#41535b", }, -- DevIconDsStore xxx ctermfg=59 guifg=#41535b
    DevIconSig                             { fg="#e37933", }, -- DevIconSig     xxx ctermfg=173 guifg=#e37933
    DevIconSwift                           { fg="#e37933", }, -- DevIconSwift   xxx ctermfg=173 guifg=#e37933
    DevIconGitAttributes                   { fg="#41535b", }, -- DevIconGitAttributes xxx ctermfg=59 guifg=#41535b
    DevIconLess                            { fg="#563d7c", }, -- DevIconLess    xxx ctermfg=60 guifg=#563d7c
    DevIconPsb                             { fg="#519aba", }, -- DevIconPsb     xxx ctermfg=67 guifg=#519aba
    DevIconPy                              { fg="#ffbc03", }, -- DevIconPy      xxx ctermfg=61 guifg=#ffbc03
    DevIconH                               { fg="#a074c4", }, -- DevIconH       xxx ctermfg=140 guifg=#a074c4
    DevIconEx                              { fg="#a074c4", }, -- DevIconEx      xxx ctermfg=140 guifg=#a074c4
    DevIconBat                             { fg="#c1f12e", }, -- DevIconBat     xxx ctermfg=154 guifg=#C1F12E
    DevIconExs                             { fg="#a074c4", }, -- DevIconExs     xxx ctermfg=140 guifg=#a074c4
    DevIconKotlin                          { fg="#f88a02", }, -- DevIconKotlin  xxx ctermfg=208 guifg=#F88A02
    DevIconPyc                             { fg="#ffe291", }, -- DevIconPyc     xxx ctermfg=67 guifg=#ffe291
    DevIconJl                              { fg="#a270ba", }, -- DevIconJl      xxx ctermfg=133 guifg=#a270ba
    DevIconCoffee                          { fg="#cbcb41", }, -- DevIconCoffee  xxx ctermfg=185 guifg=#cbcb41
    DevIconErb                             { fg="#701516", }, -- DevIconErb     xxx ctermfg=52 guifg=#701516
    DevIconHbs                             { fg="#f0772b", }, -- DevIconHbs     xxx ctermfg=208 guifg=#f0772b
    DevIconDiff                            { fg="#41535b", }, -- DevIconDiff    xxx ctermfg=59 guifg=#41535b
    DevIconZig                             { fg="#f69a1b", }, -- DevIconZig     xxx ctermfg=208 guifg=#f69a1b
    DevIconPm                              { fg="#519aba", }, -- DevIconPm      xxx ctermfg=67 guifg=#519aba
    DevIconBabelrc                         { fg="#cbcb41", }, -- DevIconBabelrc xxx ctermfg=185 guifg=#cbcb41
    DevIconRlib                            { fg="#dea584", }, -- DevIconRlib    xxx ctermfg=180 guifg=#dea584
    DevIconDockerfile                      { fg="#384d54", }, -- DevIconDockerfile xxx ctermfg=59 guifg=#384d54
    DevIconWebp                            { fg="#a074c4", }, -- DevIconWebp    xxx ctermfg=140 guifg=#a074c4
    DevIconXcPlayground                    { fg="#e37933", }, -- DevIconXcPlayground xxx ctermfg=173 guifg=#e37933
    DevIconRproj                           { fg="#358a5b", }, -- DevIconRproj   xxx ctermfg=65 guifg=#358a5b
    DevIconGemspec                         { fg="#701516", }, -- DevIconGemspec xxx ctermfg=52 guifg=#701516
    DevIconDesktopEntry                    { fg="#563d7c", }, -- DevIconDesktopEntry xxx ctermfg=60 guifg=#563d7c
    DevIconVagrantfile                     { fg="#1563ff", }, -- DevIconVagrantfile xxx ctermfg=27 guifg=#1563FF
    DevIconVue                             { fg="#8dc149", }, -- DevIconVue     xxx ctermfg=107 guifg=#8dc149
    DevIconJson                            { fg="#cbcb41", }, -- DevIconJson    xxx ctermfg=185 guifg=#cbcb41
    DevIconPdf                             { fg="#b30b00", }, -- DevIconPdf     xxx ctermfg=124 guifg=#b30b00
    DevIconGvimrc                          { fg="#019833", }, -- DevIconGvimrc  xxx ctermfg=29 guifg=#019833
    DevIconDefault                         { fg="#6d8086", }, -- DevIconDefault xxx ctermfg=66 guifg=#6d8086
    DevIconMarkdown                        { fg="#519aba", }, -- DevIconMarkdown xxx ctermfg=67 guifg=#519aba
    DevIconElm                             { fg="#519aba", }, -- DevIconElm     xxx ctermfg=67 guifg=#519aba
    DevIconHtml                            { fg="#e34c26", }, -- DevIconHtml    xxx ctermfg=166 guifg=#e34c26
    DevIconGitIgnore                       { fg="#41535b", }, -- DevIconGitIgnore xxx ctermfg=59 guifg=#41535b
    DevIconSln                             { fg="#854cc7", }, -- DevIconSln     xxx ctermfg=98 guifg=#854CC7
    DevIconCrystal                         { fg="#000000", }, -- DevIconCrystal xxx ctermfg=16 guifg=#000000
    DevIconTextScene                       { fg="#a074c4", }, -- DevIconTextScene xxx ctermfg=140 guifg=#a074c4
    DevIconConf                            { fg="#6d8086", }, -- DevIconConf    xxx ctermfg=66 guifg=#6d8086
    DevIconBashrc                          { fg="#89e051", }, -- DevIconBashrc  xxx ctermfg=113 guifg=#89e051
    DevIconGodotProject                    { fg="#6d8086", }, -- DevIconGodotProject xxx ctermfg=66 guifg=#6d8086
    DevIconStyl                            { fg="#8dc149", }, -- DevIconStyl    xxx ctermfg=107 guifg=#8dc149
    DevIconNix                             { fg="#7ebae4", }, -- DevIconNix     xxx ctermfg=110 guifg=#7ebae4
    DevIconTextResource                    { fg="#cbcb41", }, -- DevIconTextResource xxx ctermfg=185 guifg=#cbcb41
    DevIconClojureJS                       { fg="#519aba", }, -- DevIconClojureJS xxx ctermfg=67 guifg=#519aba
    DevIconBinaryGLTF                      { fg="#ffb13b", }, -- DevIconBinaryGLTF xxx ctermfg=215 guifg=#FFB13B
    DevIconSettingsJson                    { fg="#854cc7", }, -- DevIconSettingsJson xxx ctermfg=98 guifg=#854CC7
    DevIconFsharp                          { fg="#519aba", }, -- DevIconFsharp  xxx ctermfg=67 guifg=#519aba
    DevIconMakefile                        { fg="#6d8086", }, -- DevIconMakefile xxx ctermfg=66 guifg=#6d8086
    DevIconYaml                            { fg="#6d8086", }, -- DevIconYaml    xxx ctermfg=66 guifg=#6d8086
    DevIconBashProfile                     { fg="#89e051", }, -- DevIconBashProfile xxx ctermfg=113 guifg=#89e051
    DevIconJsx                             { fg="#519aba", }, -- DevIconJsx     xxx ctermfg=67 guifg=#519aba
    DevIconPromptPs1                       { fg="#4d5a5e", }, -- DevIconPromptPs1 xxx ctermfg=59 guifg=#4d5a5e
    DevIconFs                              { fg="#519aba", }, -- DevIconFs      xxx ctermfg=67 guifg=#519aba
    DevIconTor                             { fg="#519aba", }, -- DevIconTor     xxx ctermfg=67 guifg=#519aba
    DevIconGDScript                        { fg="#6d8086", }, -- DevIconGDScript xxx ctermfg=66 guifg=#6d8086
    DevIconC                               { fg="#599eff", }, -- DevIconC       xxx ctermfg=75 guifg=#599eff
    DevIconRss                             { fg="#fb9d3b", }, -- DevIconRss     xxx ctermfg=215 guifg=#FB9D3B
    DevIconGitlabCI                        { fg="#e24329", }, -- DevIconGitlabCI xxx ctermfg=166 guifg=#e24329
    DevIconGo                              { fg="#519aba", }, -- DevIconGo      xxx ctermfg=67 guifg=#519aba
    DevIconXml                             { fg="#e37933", }, -- DevIconXml     xxx ctermfg=173 guifg=#e37933
    DevIconGitConfig                       { fg="#41535b", }, -- DevIconGitConfig xxx ctermfg=59 guifg=#41535b
    DevIconCpp                             { fg="#519aba", }, -- DevIconCpp     xxx ctermfg=67 guifg=#519aba
    DevIconPackedResource                  { fg="#6d8086", }, -- DevIconPackedResource xxx ctermfg=66 guifg=#6d8086
    DevIconVim                             { fg="#019833", }, -- DevIconVim     xxx ctermfg=29 guifg=#019833
    DevIconHtm                             { fg="#e34c26", }, -- DevIconHtm     xxx ctermfg=166 guifg=#e34c26
    DevIconConfigRu                        { fg="#701516", }, -- DevIconConfigRu xxx ctermfg=52 guifg=#701516
    DevIconGitCommit                       { fg="#41535b", }, -- DevIconGitCommit xxx ctermfg=59 guifg=#41535b
    DevIconWebpack                         { fg="#519aba", }, -- DevIconWebpack xxx ctermfg=67 guifg=#519aba
    DevIconClojure                         { fg="#8dc149", }, -- DevIconClojure xxx ctermfg=107 guifg=#8dc149
    DevIconNodeModules                     { fg="#e8274b", }, -- DevIconNodeModules xxx ctermfg=161 guifg=#E8274B
    DevIconProlog                          { fg="#e4b854", }, -- DevIconProlog  xxx ctermfg=179 guifg=#e4b854
    DevIconToml                            { fg="#6d8086", }, -- DevIconToml    xxx ctermfg=66 guifg=#6d8086
    DevIconCson                            { fg="#cbcb41", }, -- DevIconCson    xxx ctermfg=185 guifg=#cbcb41
    DevIconPyd                             { fg="#ffe291", }, -- DevIconPyd     xxx ctermfg=67 guifg=#ffe291
    DevIconAwk                             { fg="#4d5a5e", }, -- DevIconAwk     xxx ctermfg=59 guifg=#4d5a5e
    DevIconHh                              { fg="#a074c4", }, -- DevIconHh      xxx ctermfg=140 guifg=#a074c4
    DevIconMdx                             { fg="#519aba", }, -- DevIconMdx     xxx ctermfg=67 guifg=#519aba
    DevIconEdn                             { fg="#519aba", }, -- DevIconEdn     xxx ctermfg=67 guifg=#519aba
    DevIconBmp                             { fg="#a074c4", }, -- DevIconBmp     xxx ctermfg=140 guifg=#a074c4
    DevIconPl                              { fg="#519aba", }, -- DevIconPl      xxx ctermfg=67 guifg=#519aba
    DevIconXul                             { fg="#e37933", }, -- DevIconXul     xxx ctermfg=173 guifg=#e37933
    DevIconHs                              { fg="#a074c4", }, -- DevIconHs      xxx ctermfg=140 guifg=#a074c4
    DevIconSml                             { fg="#e37933", }, -- DevIconSml     xxx ctermfg=173 guifg=#e37933
    DevIconZshprofile                      { fg="#89e051", }, -- DevIconZshprofile xxx ctermfg=113 guifg=#89e051
    DevIconHxx                             { fg="#a074c4", }, -- DevIconHxx     xxx ctermfg=140 guifg=#a074c4
    DevIconMli                             { fg="#e37933", }, -- DevIconMli     xxx ctermfg=173 guifg=#e37933
    DevIconSvelte                          { fg="#ff3e00", }, -- DevIconSvelte  xxx ctermfg=202 guifg=#ff3e00
    DevIconNPMIgnore                       { fg="#e8274b", }, -- DevIconNPMIgnore xxx ctermfg=161 guifg=#E8274B
    DevIconDb                              { fg="#dad8d8", }, -- DevIconDb      xxx ctermfg=188 guifg=#dad8d8
    DevIconSass                            { fg="#f55385", }, -- DevIconSass    xxx ctermfg=204 guifg=#f55385
    DevIconSvg                             { fg="#ffb13b", }, -- DevIconSvg     xxx ctermfg=215 guifg=#FFB13B
    DevIconCsv                             { fg="#89e051", }, -- DevIconCsv     xxx ctermfg=113 guifg=#89e051
    DevIconMustache                        { fg="#e37933", }, -- DevIconMustache xxx ctermfg=173 guifg=#e37933
    DevIconFavicon                         { fg="#cbcb41", }, -- DevIconFavicon xxx ctermfg=185 guifg=#cbcb41
    DevIconBrewfile                        { fg="#701516", }, -- DevIconBrewfile xxx ctermfg=52 guifg=#701516
    DevIconEex                             { fg="#a074c4", }, -- DevIconEex     xxx ctermfg=140 guifg=#a074c4
    DevIconCxx                             { fg="#519aba", }, -- DevIconCxx     xxx ctermfg=67 guifg=#519aba
    DevIconCs                              { fg="#596706", }, -- DevIconCs      xxx ctermfg=58 guifg=#596706
    DevIconCMakeLists                      { fg="#6d8086", }, -- DevIconCMakeLists xxx ctermfg=66 guifg=#6d8086
    DevIconPng                             { fg="#a074c4", }, -- DevIconPng     xxx ctermfg=140 guifg=#a074c4
    DevIconTxt                             { fg="#89e051", }, -- DevIconTxt     xxx ctermfg=113 guifg=#89e051
    DevIconPsd                             { fg="#519aba", }, -- DevIconPsd     xxx ctermfg=67 guifg=#519aba
    DevIconSh                              { fg="#4d5a5e", }, -- DevIconSh      xxx ctermfg=59 guifg=#4d5a5e
    DevIconEpp                             { fg="#ffa61a", }, -- DevIconEpp     xxx guifg=#FFA61A
    DevIconAi                              { fg="#cbcb41", }, -- DevIconAi      xxx ctermfg=185 guifg=#cbcb41
    DevIconPyo                             { fg="#ffe291", }, -- DevIconPyo     xxx ctermfg=67 guifg=#ffe291
    DevIconR                               { fg="#358a5b", }, -- DevIconR       xxx ctermfg=65 guifg=#358a5b
    DevIconDump                            { fg="#dad8d8", }, -- DevIconDump    xxx ctermfg=188 guifg=#dad8d8
    DevIconYml                             { fg="#6d8086", }, -- DevIconYml     xxx ctermfg=66 guifg=#6d8086
    DevIconRs                              { fg="#dea584", }, -- DevIconRs      xxx ctermfg=180 guifg=#dea584
    DevIconGruntfile                       { fg="#e37933", }, -- DevIconGruntfile xxx ctermfg=173 guifg=#e37933
    DevIconScala                           { fg="#cc3e44", }, -- DevIconScala   xxx ctermfg=167 guifg=#cc3e44
    DevIconScss                            { fg="#f55385", }, -- DevIconScss    xxx ctermfg=204 guifg=#f55385
    DevIconFsi                             { fg="#519aba", }, -- DevIconFsi     xxx ctermfg=67 guifg=#519aba
    DevIconFsscript                        { fg="#519aba", }, -- DevIconFsscript xxx ctermfg=67 guifg=#519aba
    DevIconGulpfile                        { fg="#cc3e44", }, -- DevIconGulpfile xxx ctermfg=167 guifg=#cc3e44
    DevIconFsx                             { fg="#519aba", }, -- DevIconFsx     xxx ctermfg=67 guifg=#519aba
    DevIconTs                              { fg="#519aba", }, -- DevIconTs      xxx ctermfg=67 guifg=#519aba
    DevIconTsx                             { fg="#519aba", }, -- DevIconTsx     xxx ctermfg=67 guifg=#519aba
    DevIconHpp                             { fg="#a074c4", }, -- DevIconHpp     xxx ctermfg=140 guifg=#a074c4
    DevIconDropbox                         { fg="#0061fe", }, -- DevIconDropbox xxx ctermfg=27 guifg=#0061FE
    DevIconFish                            { fg="#4d5a5e", }, -- DevIconFish    xxx ctermfg=59 guifg=#4d5a5e
    DevIconRake                            { fg="#701516", }, -- DevIconRake    xxx ctermfg=52 guifg=#701516
    DevIconWebmanifest                     { fg="#f1e05a", }, -- DevIconWebmanifest xxx ctermfg=221 guifg=#f1e05a
    DevIconMd                              { fg="#519aba", }, -- DevIconMd      xxx ctermfg=67 guifg=#519aba
    DevIconXls                             { fg="#207245", }, -- DevIconXls     xxx ctermfg=23 guifg=#207245
    DevIconEjs                             { fg="#cbcb41", }, -- DevIconEjs     xxx ctermfg=185 guifg=#cbcb41
    DevIconJs                              { fg="#cbcb41", }, -- DevIconJs      xxx ctermfg=185 guifg=#cbcb41
    DevIconDart                            { fg="#03589c", }, -- DevIconDart    xxx ctermfg=25 guifg=#03589C
    DevIconConfiguration                   { fg="#ececec", }, -- DevIconConfiguration xxx ctermfg=231 guifg=#ECECEC
    DevIconTerminal                        { fg="#31b53e", }, -- DevIconTerminal xxx ctermfg=71 guifg=#31B53E
    DevIconGemfile                         { fg="#701516", }, -- DevIconGemfile xxx ctermfg=52 guifg=#701516
    NvimTreeFolderIcon                     { fg="#8094b4", }, -- NvimTreeFolderIcon xxx guifg=#8094b4
    NvimTreeExecFile                       { gui="bold", fg="#34d058", }, -- NvimTreeExecFile xxx gui=bold guifg=#34d058
    NvimTreeWindowPicker                   { gui="bold", fg="#ededed", bg="#4493c8", }, -- NvimTreeWindowPicker xxx gui=bold guifg=#ededed guibg=#4493c8
    NvimTreeOpenedFile                     { gui="bold", fg="#34d058", }, -- NvimTreeOpenedFile xxx gui=bold guifg=#34d058
    NvimTreeGitStaged                      { fg="#34d058", }, -- NvimTreeGitStaged xxx guifg=#34d058
    NvimTreeFileStaged                     { NvimTreeGitStaged }, -- NvimTreeFileStaged xxx links to NvimTreeGitStaged
    NvimTreeGitMerge                       { fg="#ffea7f", }, -- NvimTreeGitMerge xxx guifg=#ffea7f
    NvimTreeFileMerge                      { NvimTreeGitMerge }, -- NvimTreeFileMerge xxx links to NvimTreeGitMerge
    CmpItemAbbrDefault                     { fg="#c9d1d9", }, -- CmpItemAbbrDefault xxx guifg=#c9d1d9
    CmpItemAbbr                            { CmpItemAbbrDefault }, -- CmpItemAbbr    xxx links to CmpItemAbbrDefault
    CmpItemAbbrDeprecatedDefault           { fg="#6a737d", }, -- CmpItemAbbrDeprecatedDefault xxx guifg=#6a737d
    CmpItemAbbrMatchDefault                { fg="#c9d1d9", }, -- CmpItemAbbrMatchDefault xxx guifg=#c9d1d9
    CmpItemAbbrMatchFuzzyDefault           { fg="#c9d1d9", }, -- CmpItemAbbrMatchFuzzyDefault xxx guifg=#c9d1d9
    CmpItemKindDefault                     { fg="#79b8ff", }, -- CmpItemKindDefault xxx guifg=#79b8ff
    CmpItemMenuDefault                     { fg="#c9d1d9", }, -- CmpItemMenuDefault xxx guifg=#c9d1d9
    CmpItemMenu                            { CmpItemMenuDefault }, -- CmpItemMenu    xxx links to CmpItemMenuDefault
    TSNone                                 { fg="foreground", }, -- TSNone         xxx guifg=foreground
    TSText                                 { TSNone }, -- TSText         xxx links to TSNone
    TSStrong                               { gui="bold", }, -- TSStrong       xxx cterm=bold gui=bold
    TSEmphasis                             { gui="italic", }, -- TSEmphasis     xxx cterm=italic gui=italic
    TSUnderline                            { gui="underline", }, -- TSUnderline    xxx cterm=underline gui=underline
    TSStrike                               { gui="strikethrough", }, -- TSStrike       xxx cterm=strikethrough gui=strikethrough
    lualine_a_normal                       { fg="#24292e", bg="#2188ff", }, -- lualine_a_normal xxx guifg=#24292e guibg=#2188ff
    lualine_c_normal                       { fg="#86b4e8", bg="#1f252a", }, -- lualine_c_normal xxx guifg=#86B4E8 guibg=#1F252A
    lualine_b_normal                       { fg="#a7c2e1", bg="#233c58", }, -- lualine_b_normal xxx guifg=#A7C2E1 guibg=#233C58
    lualine_a_insert                       { fg="#24292e", bg="#34d058", }, -- lualine_a_insert xxx guifg=#24292e guibg=#34d058
    lualine_16_no_mode                     { lualine_a_insert }, -- lualine_16_no_mode xxx links to lualine_a_insert
    lualine_c_insert                       { fg="#8dd1a5", bg="#1f2628", }, -- lualine_c_insert xxx guifg=#8DD1A5 guibg=#1F2628
    lualine_b_insert                       { fg="#abd1bf", bg="#274a36", }, -- lualine_b_insert xxx guifg=#ABD1BF guibg=#274A36
    lualine_a_visual                       { fg="#24292e", bg="#ffea7f", }, -- lualine_a_visual xxx guifg=#24292e guibg=#ffea7f
    lualine_c_visual                       { fg="#dfdbb5", bg="#212629", }, -- lualine_c_visual xxx guifg=#DFDBB5 guibg=#212629
    lualine_b_visual                       { fg="#d4d6c7", bg="#50503e", }, -- lualine_b_visual xxx guifg=#D4D6C7 guibg=#50503E
    lualine_a_terminal                     { fg="#24292e", bg="#d18616", }, -- lualine_a_terminal xxx guifg=#24292e guibg=#d18616
    lualine_c_terminal                     { fg="#ccb38b", bg="#212528", }, -- lualine_c_terminal xxx guifg=#CCB38B guibg=#212528
    lualine_b_terminal                     { fg="#cbc2b2", bg="#473c29", }, -- lualine_b_terminal xxx guifg=#CBC2B2 guibg=#473C29
    lualine_a_inactive                     { fg="#565b61", bg="#1f2428", }, -- lualine_a_inactive xxx guifg=#565B61 guibg=#1f2428
    lualine_c_inactive                     { fg="#565b61", bg="#1f2428", }, -- lualine_c_inactive xxx guifg=#565B61 guibg=#1f2428
    lualine_b_inactive                     { fg="#565b61", bg="#1f2428", }, -- lualine_b_inactive xxx guifg=#565B61 guibg=#1f2428
    lualine_a_command                      { fg="#24292e", bg="#b392f0", }, -- lualine_a_command xxx guifg=#24292e guibg=#b392f0
    lualine_c_command                      { fg="#c0b8e2", bg="#20252a", }, -- lualine_c_command xxx guifg=#C0B8E2 guibg=#20252A
    lualine_b_command                      { fg="#c5c4de", bg="#413e55", }, -- lualine_b_command xxx guifg=#C5C4DE guibg=#413E55
    lualine_a_replace                      { fg="#24292e", bg="#ea4a5a", }, -- lualine_a_replace xxx guifg=#24292e guibg=#ea4a5a
    lualine_c_replace                      { fg="#d69ba6", bg="#212429", }, -- lualine_c_replace xxx guifg=#D69BA6 guibg=#212429
    lualine_b_replace                      { fg="#d0b6c0", bg="#4c3037", }, -- lualine_b_replace xxx guifg=#D0B6C0 guibg=#4C3037
    lualine_c_diff_added_normal            { fg="#28a745", bg="#1f252a", }, -- lualine_c_diff_added_normal xxx guifg=#28a745 guibg=#1F252A
    lualine_c_diff_added_insert            { fg="#28a745", bg="#1f2628", }, -- lualine_c_diff_added_insert xxx guifg=#28a745 guibg=#1F2628
    lualine_c_diff_added_visual            { fg="#28a745", bg="#212629", }, -- lualine_c_diff_added_visual xxx guifg=#28a745 guibg=#212629
    lualine_c_diff_added_replace           { fg="#28a745", bg="#212429", }, -- lualine_c_diff_added_replace xxx guifg=#28a745 guibg=#212429
    lualine_c_diff_added_command           { fg="#28a745", bg="#20252a", }, -- lualine_c_diff_added_command xxx guifg=#28a745 guibg=#20252A
    lualine_c_diff_added_terminal          { fg="#28a745", bg="#212528", }, -- lualine_c_diff_added_terminal xxx guifg=#28a745 guibg=#212528
    lualine_c_diff_added_inactive          { fg="#28a745", bg="#1f2428", }, -- lualine_c_diff_added_inactive xxx guifg=#28a745 guibg=#1f2428
    lualine_c_diff_modified_normal         { fg="#2188ff", bg="#1f252a", }, -- lualine_c_diff_modified_normal xxx guifg=#2188ff guibg=#1F252A
    lualine_c_diff_modified_insert         { fg="#2188ff", bg="#1f2628", }, -- lualine_c_diff_modified_insert xxx guifg=#2188ff guibg=#1F2628
    lualine_c_diff_modified_visual         { fg="#2188ff", bg="#212629", }, -- lualine_c_diff_modified_visual xxx guifg=#2188ff guibg=#212629
    lualine_c_diff_modified_replace        { fg="#2188ff", bg="#212429", }, -- lualine_c_diff_modified_replace xxx guifg=#2188ff guibg=#212429
    lualine_c_diff_modified_command        { fg="#2188ff", bg="#20252a", }, -- lualine_c_diff_modified_command xxx guifg=#2188ff guibg=#20252A
    lualine_c_diff_modified_terminal       { fg="#2188ff", bg="#212528", }, -- lualine_c_diff_modified_terminal xxx guifg=#2188ff guibg=#212528
    lualine_c_diff_modified_inactive       { fg="#2188ff", bg="#1f2428", }, -- lualine_c_diff_modified_inactive xxx guifg=#2188ff guibg=#1f2428
    lualine_c_diff_removed_normal          { fg="#ea4a5a", bg="#1f252a", }, -- lualine_c_diff_removed_normal xxx guifg=#ea4a5a guibg=#1F252A
    lualine_c_diff_removed_insert          { fg="#ea4a5a", bg="#1f2628", }, -- lualine_c_diff_removed_insert xxx guifg=#ea4a5a guibg=#1F2628
    lualine_c_diff_removed_visual          { fg="#ea4a5a", bg="#212629", }, -- lualine_c_diff_removed_visual xxx guifg=#ea4a5a guibg=#212629
    lualine_c_diff_removed_replace         { fg="#ea4a5a", bg="#212429", }, -- lualine_c_diff_removed_replace xxx guifg=#ea4a5a guibg=#212429
    lualine_c_diff_removed_command         { fg="#ea4a5a", bg="#20252a", }, -- lualine_c_diff_removed_command xxx guifg=#ea4a5a guibg=#20252A
    lualine_c_diff_removed_terminal        { fg="#ea4a5a", bg="#212528", }, -- lualine_c_diff_removed_terminal xxx guifg=#ea4a5a guibg=#212528
    lualine_c_diff_removed_inactive        { fg="#ea4a5a", bg="#1f2428", }, -- lualine_c_diff_removed_inactive xxx guifg=#ea4a5a guibg=#1f2428
    lualine_c_diagnostics_error_normal     { fg="#f97583", bg="#1f252a", }, -- lualine_c_diagnostics_error_normal xxx guifg=#f97583 guibg=#1F252A
    lualine_c_diagnostics_error_insert     { fg="#f97583", bg="#1f2628", }, -- lualine_c_diagnostics_error_insert xxx guifg=#f97583 guibg=#1F2628
    lualine_c_diagnostics_error_visual     { fg="#f97583", bg="#212629", }, -- lualine_c_diagnostics_error_visual xxx guifg=#f97583 guibg=#212629
    lualine_c_diagnostics_error_replace    { fg="#f97583", bg="#212429", }, -- lualine_c_diagnostics_error_replace xxx guifg=#f97583 guibg=#212429
    lualine_c_diagnostics_error_command    { fg="#f97583", bg="#20252a", }, -- lualine_c_diagnostics_error_command xxx guifg=#f97583 guibg=#20252A
    lualine_c_diagnostics_error_terminal   { fg="#f97583", bg="#212528", }, -- lualine_c_diagnostics_error_terminal xxx guifg=#f97583 guibg=#212528
    lualine_c_diagnostics_error_inactive   { fg="#f97583", bg="#1f2428", }, -- lualine_c_diagnostics_error_inactive xxx guifg=#f97583 guibg=#1f2428
    lualine_c_diagnostics_warn_normal      { fg="#cca700", bg="#1f252a", }, -- lualine_c_diagnostics_warn_normal xxx guifg=#cca700 guibg=#1F252A
    lualine_c_diagnostics_warn_insert      { fg="#cca700", bg="#1f2628", }, -- lualine_c_diagnostics_warn_insert xxx guifg=#cca700 guibg=#1F2628
    lualine_c_diagnostics_warn_visual      { fg="#cca700", bg="#212629", }, -- lualine_c_diagnostics_warn_visual xxx guifg=#cca700 guibg=#212629
    lualine_c_diagnostics_warn_replace     { fg="#cca700", bg="#212429", }, -- lualine_c_diagnostics_warn_replace xxx guifg=#cca700 guibg=#212429
    lualine_c_diagnostics_warn_command     { fg="#cca700", bg="#20252a", }, -- lualine_c_diagnostics_warn_command xxx guifg=#cca700 guibg=#20252A
    lualine_c_diagnostics_warn_terminal    { fg="#cca700", bg="#212528", }, -- lualine_c_diagnostics_warn_terminal xxx guifg=#cca700 guibg=#212528
    lualine_c_diagnostics_warn_inactive    { fg="#cca700", bg="#1f2428", }, -- lualine_c_diagnostics_warn_inactive xxx guifg=#cca700 guibg=#1f2428
    lualine_c_diagnostics_info_normal      { fg="#75beff", bg="#1f252a", }, -- lualine_c_diagnostics_info_normal xxx guifg=#75beff guibg=#1F252A
    lualine_c_diagnostics_info_insert      { fg="#75beff", bg="#1f2628", }, -- lualine_c_diagnostics_info_insert xxx guifg=#75beff guibg=#1F2628
    lualine_c_diagnostics_info_visual      { fg="#75beff", bg="#212629", }, -- lualine_c_diagnostics_info_visual xxx guifg=#75beff guibg=#212629
    lualine_c_diagnostics_info_replace     { fg="#75beff", bg="#212429", }, -- lualine_c_diagnostics_info_replace xxx guifg=#75beff guibg=#212429
    lualine_c_diagnostics_info_command     { fg="#75beff", bg="#20252a", }, -- lualine_c_diagnostics_info_command xxx guifg=#75beff guibg=#20252A
    lualine_c_diagnostics_info_terminal    { fg="#75beff", bg="#212528", }, -- lualine_c_diagnostics_info_terminal xxx guifg=#75beff guibg=#212528
    lualine_c_diagnostics_info_inactive    { fg="#75beff", bg="#1f2428", }, -- lualine_c_diagnostics_info_inactive xxx guifg=#75beff guibg=#1f2428
    lualine_c_diagnostics_hint_normal      { fg="#eeeeb3", bg="#1f252a", }, -- lualine_c_diagnostics_hint_normal xxx guifg=#eeeeb3 guibg=#1F252A
    lualine_c_diagnostics_hint_insert      { fg="#eeeeb3", bg="#1f2628", }, -- lualine_c_diagnostics_hint_insert xxx guifg=#eeeeb3 guibg=#1F2628
    lualine_c_diagnostics_hint_visual      { fg="#eeeeb3", bg="#212629", }, -- lualine_c_diagnostics_hint_visual xxx guifg=#eeeeb3 guibg=#212629
    lualine_c_diagnostics_hint_replace     { fg="#eeeeb3", bg="#212429", }, -- lualine_c_diagnostics_hint_replace xxx guifg=#eeeeb3 guibg=#212429
    lualine_c_diagnostics_hint_command     { fg="#eeeeb3", bg="#20252a", }, -- lualine_c_diagnostics_hint_command xxx guifg=#eeeeb3 guibg=#20252A
    lualine_c_diagnostics_hint_terminal    { fg="#eeeeb3", bg="#212528", }, -- lualine_c_diagnostics_hint_terminal xxx guifg=#eeeeb3 guibg=#212528
    lualine_c_diagnostics_hint_inactive    { fg="#eeeeb3", bg="#1f2428", }, -- lualine_c_diagnostics_hint_inactive xxx guifg=#eeeeb3 guibg=#1f2428
    lualine_c_diff_added_0_normal          { fg="#28a745", bg="#1f252a", }, -- lualine_c_diff_added_0_normal xxx guifg=#28a745 guibg=#1F252A
    lualine_c_diff_added_0_insert          { fg="#28a745", bg="#1f2628", }, -- lualine_c_diff_added_0_insert xxx guifg=#28a745 guibg=#1F2628
    lualine_c_diff_added_0_visual          { fg="#28a745", bg="#212629", }, -- lualine_c_diff_added_0_visual xxx guifg=#28a745 guibg=#212629
    lualine_c_diff_added_0_replace         { fg="#28a745", bg="#212429", }, -- lualine_c_diff_added_0_replace xxx guifg=#28a745 guibg=#212429
    lualine_c_diff_added_0_command         { fg="#28a745", bg="#20252a", }, -- lualine_c_diff_added_0_command xxx guifg=#28a745 guibg=#20252A
    lualine_c_diff_added_0_terminal        { fg="#28a745", bg="#212528", }, -- lualine_c_diff_added_0_terminal xxx guifg=#28a745 guibg=#212528
    lualine_c_diff_added_0_inactive        { fg="#28a745", bg="#1f2428", }, -- lualine_c_diff_added_0_inactive xxx guifg=#28a745 guibg=#1f2428
    lualine_c_diff_modified_0_normal       { fg="#2188ff", bg="#1f252a", }, -- lualine_c_diff_modified_0_normal xxx guifg=#2188ff guibg=#1F252A
    lualine_c_diff_modified_0_insert       { fg="#2188ff", bg="#1f2628", }, -- lualine_c_diff_modified_0_insert xxx guifg=#2188ff guibg=#1F2628
    lualine_c_diff_modified_0_visual       { fg="#2188ff", bg="#212629", }, -- lualine_c_diff_modified_0_visual xxx guifg=#2188ff guibg=#212629
    lualine_c_diff_modified_0_replace      { fg="#2188ff", bg="#212429", }, -- lualine_c_diff_modified_0_replace xxx guifg=#2188ff guibg=#212429
    lualine_c_diff_modified_0_command      { fg="#2188ff", bg="#20252a", }, -- lualine_c_diff_modified_0_command xxx guifg=#2188ff guibg=#20252A
    lualine_c_diff_modified_0_terminal     { fg="#2188ff", bg="#212528", }, -- lualine_c_diff_modified_0_terminal xxx guifg=#2188ff guibg=#212528
    lualine_c_diff_modified_0_inactive     { fg="#2188ff", bg="#1f2428", }, -- lualine_c_diff_modified_0_inactive xxx guifg=#2188ff guibg=#1f2428
    lualine_c_diff_removed_0_normal        { fg="#ea4a5a", bg="#1f252a", }, -- lualine_c_diff_removed_0_normal xxx guifg=#ea4a5a guibg=#1F252A
    lualine_c_diff_removed_0_insert        { fg="#ea4a5a", bg="#1f2628", }, -- lualine_c_diff_removed_0_insert xxx guifg=#ea4a5a guibg=#1F2628
    lualine_c_diff_removed_0_visual        { fg="#ea4a5a", bg="#212629", }, -- lualine_c_diff_removed_0_visual xxx guifg=#ea4a5a guibg=#212629
    lualine_c_diff_removed_0_replace       { fg="#ea4a5a", bg="#212429", }, -- lualine_c_diff_removed_0_replace xxx guifg=#ea4a5a guibg=#212429
    lualine_c_diff_removed_0_command       { fg="#ea4a5a", bg="#20252a", }, -- lualine_c_diff_removed_0_command xxx guifg=#ea4a5a guibg=#20252A
    lualine_c_diff_removed_0_terminal      { fg="#ea4a5a", bg="#212528", }, -- lualine_c_diff_removed_0_terminal xxx guifg=#ea4a5a guibg=#212528
    lualine_c_diff_removed_0_inactive      { fg="#ea4a5a", bg="#1f2428", }, -- lualine_c_diff_removed_0_inactive xxx guifg=#ea4a5a guibg=#1f2428
    lualine_c_diagnostics_error_0_normal   { fg="#f97583", bg="#1f252a", }, -- lualine_c_diagnostics_error_0_normal xxx guifg=#f97583 guibg=#1F252A
    lualine_c_diagnostics_error_0_insert   { fg="#f97583", bg="#1f2628", }, -- lualine_c_diagnostics_error_0_insert xxx guifg=#f97583 guibg=#1F2628
    lualine_c_diagnostics_error_0_visual   { fg="#f97583", bg="#212629", }, -- lualine_c_diagnostics_error_0_visual xxx guifg=#f97583 guibg=#212629
    lualine_c_diagnostics_error_0_replace  { fg="#f97583", bg="#212429", }, -- lualine_c_diagnostics_error_0_replace xxx guifg=#f97583 guibg=#212429
    lualine_c_diagnostics_error_0_command  { fg="#f97583", bg="#20252a", }, -- lualine_c_diagnostics_error_0_command xxx guifg=#f97583 guibg=#20252A
    lualine_c_diagnostics_error_0_terminal { fg="#f97583", bg="#212528", }, -- lualine_c_diagnostics_error_0_terminal xxx guifg=#f97583 guibg=#212528
    lualine_c_diagnostics_error_0_inactive { fg="#f97583", bg="#1f2428", }, -- lualine_c_diagnostics_error_0_inactive xxx guifg=#f97583 guibg=#1f2428
    lualine_c_diagnostics_warn_0_normal    { fg="#cca700", bg="#1f252a", }, -- lualine_c_diagnostics_warn_0_normal xxx guifg=#cca700 guibg=#1F252A
    lualine_c_diagnostics_warn_0_insert    { fg="#cca700", bg="#1f2628", }, -- lualine_c_diagnostics_warn_0_insert xxx guifg=#cca700 guibg=#1F2628
    lualine_c_diagnostics_warn_0_visual    { fg="#cca700", bg="#212629", }, -- lualine_c_diagnostics_warn_0_visual xxx guifg=#cca700 guibg=#212629
    lualine_c_diagnostics_warn_0_replace   { fg="#cca700", bg="#212429", }, -- lualine_c_diagnostics_warn_0_replace xxx guifg=#cca700 guibg=#212429
    lualine_c_diagnostics_warn_0_command   { fg="#cca700", bg="#20252a", }, -- lualine_c_diagnostics_warn_0_command xxx guifg=#cca700 guibg=#20252A
    lualine_c_diagnostics_warn_0_terminal  { fg="#cca700", bg="#212528", }, -- lualine_c_diagnostics_warn_0_terminal xxx guifg=#cca700 guibg=#212528
    lualine_c_diagnostics_warn_0_inactive  { fg="#cca700", bg="#1f2428", }, -- lualine_c_diagnostics_warn_0_inactive xxx guifg=#cca700 guibg=#1f2428
    lualine_c_diagnostics_info_0_normal    { fg="#75beff", bg="#1f252a", }, -- lualine_c_diagnostics_info_0_normal xxx guifg=#75beff guibg=#1F252A
    lualine_c_diagnostics_info_0_insert    { fg="#75beff", bg="#1f2628", }, -- lualine_c_diagnostics_info_0_insert xxx guifg=#75beff guibg=#1F2628
    lualine_c_diagnostics_info_0_visual    { fg="#75beff", bg="#212629", }, -- lualine_c_diagnostics_info_0_visual xxx guifg=#75beff guibg=#212629
    lualine_c_diagnostics_info_0_replace   { fg="#75beff", bg="#212429", }, -- lualine_c_diagnostics_info_0_replace xxx guifg=#75beff guibg=#212429
    lualine_c_diagnostics_info_0_command   { fg="#75beff", bg="#20252a", }, -- lualine_c_diagnostics_info_0_command xxx guifg=#75beff guibg=#20252A
    lualine_c_diagnostics_info_0_terminal  { fg="#75beff", bg="#212528", }, -- lualine_c_diagnostics_info_0_terminal xxx guifg=#75beff guibg=#212528
    lualine_c_diagnostics_info_0_inactive  { fg="#75beff", bg="#1f2428", }, -- lualine_c_diagnostics_info_0_inactive xxx guifg=#75beff guibg=#1f2428
    lualine_c_diagnostics_hint_0_normal    { fg="#eeeeb3", bg="#1f252a", }, -- lualine_c_diagnostics_hint_0_normal xxx guifg=#eeeeb3 guibg=#1F252A
    lualine_c_diagnostics_hint_0_insert    { fg="#eeeeb3", bg="#1f2628", }, -- lualine_c_diagnostics_hint_0_insert xxx guifg=#eeeeb3 guibg=#1F2628
    lualine_c_diagnostics_hint_0_visual    { fg="#eeeeb3", bg="#212629", }, -- lualine_c_diagnostics_hint_0_visual xxx guifg=#eeeeb3 guibg=#212629
    lualine_c_diagnostics_hint_0_replace   { fg="#eeeeb3", bg="#212429", }, -- lualine_c_diagnostics_hint_0_replace xxx guifg=#eeeeb3 guibg=#212429
    lualine_c_diagnostics_hint_0_command   { fg="#eeeeb3", bg="#20252a", }, -- lualine_c_diagnostics_hint_0_command xxx guifg=#eeeeb3 guibg=#20252A
    lualine_c_diagnostics_hint_0_terminal  { fg="#eeeeb3", bg="#212528", }, -- lualine_c_diagnostics_hint_0_terminal xxx guifg=#eeeeb3 guibg=#212528
    lualine_c_diagnostics_hint_0_inactive  { fg="#eeeeb3", bg="#1f2428", }, -- lualine_c_diagnostics_hint_0_inactive xxx guifg=#eeeeb3 guibg=#1f2428
    lualine_x_DevIconLua_normal            { fg="#51a0cf", bg="#1f252a", }, -- lualine_x_DevIconLua_normal xxx guifg=#51a0cf guibg=#1F252A
    lualine_x_DevIconLua_insert            { fg="#51a0cf", bg="#1f2628", }, -- lualine_x_DevIconLua_insert xxx guifg=#51a0cf guibg=#1F2628
    lualine_x_DevIconLua_visual            { fg="#51a0cf", bg="#212629", }, -- lualine_x_DevIconLua_visual xxx guifg=#51a0cf guibg=#212629
    lualine_x_DevIconLua_replace           { fg="#51a0cf", bg="#212429", }, -- lualine_x_DevIconLua_replace xxx guifg=#51a0cf guibg=#212429
    lualine_x_DevIconLua_command           { fg="#51a0cf", bg="#20252a", }, -- lualine_x_DevIconLua_command xxx guifg=#51a0cf guibg=#20252A
    lualine_x_DevIconLua_terminal          { fg="#51a0cf", bg="#212528", }, -- lualine_x_DevIconLua_terminal xxx guifg=#51a0cf guibg=#212528
    lualine_x_DevIconLua_inactive          { fg="#51a0cf", bg="#1f2428", }, -- lualine_x_DevIconLua_inactive xxx guifg=#51a0cf guibg=#1f2428
  }
end)
return theme
